use super::{
	ValidationProfile, CASE_RULE_FDA_C112_RECOMMENDED, CASE_RULE_FDA_C112_REQUIRED,
	CASE_RULE_FDA_C171_REQUIRED, CASE_RULE_FDA_C2R2_EMAIL_REQUIRED,
	CASE_RULE_FDA_C55A_REQUIRED, CASE_RULE_FDA_C55B_REQUIRED,
	CASE_RULE_FDA_C56R_REQUIRED, CASE_RULE_FDA_D11_REQUIRED,
	CASE_RULE_FDA_D12_REQUIRED, CASE_RULE_FDA_EI32H_REQUIRED,
	CASE_RULE_FDA_GK12R11_REQUIRED, CASE_RULE_FDA_GK12R3_REQUIRED,
	CASE_RULE_FDA_GK12_REQUIRED, CASE_RULE_FDA_GK1A_CONDITIONAL,
	CASE_RULE_ICH_C11_REQUIRED, CASE_RULE_ICH_C12_REQUIRED,
	CASE_RULE_ICH_C13_REQUIRED, CASE_RULE_ICH_C14_REQUIRED,
	CASE_RULE_ICH_C15_REQUIRED, CASE_RULE_ICH_C17_REQUIRED,
	CASE_RULE_ICH_C1_REQUIRED, CASE_RULE_ICH_C2R4_REQUIRED,
	CASE_RULE_ICH_C31_REQUIRED, CASE_RULE_ICH_C32_REQUIRED,
	CASE_RULE_ICH_D1_REQUIRED, CASE_RULE_ICH_EI11A_REQUIRED,
	CASE_RULE_ICH_EI11B_REQUIRED, CASE_RULE_ICH_EI7_REQUIRED,
	CASE_RULE_ICH_FR2_REQUIRED, CASE_RULE_ICH_GK1_REQUIRED,
	CASE_RULE_ICH_GK22_REQUIRED, CASE_RULE_ICH_H1_REQUIRED,
	CASE_RULE_ICH_N_REQUIRED, CASE_RULE_MFDS_C2R4_KR1_REQUIRED,
	CASE_RULE_MFDS_C31_KR1_REQUIRED, CASE_RULE_MFDS_C54_KR1_REQUIRED,
	CASE_RULE_MFDS_D108R1_KR1A_REQUIRED, CASE_RULE_MFDS_D108R1_KR1B_REQUIRED,
	CASE_RULE_MFDS_D8R1_KR1A_REQUIRED, CASE_RULE_MFDS_D8R1_KR1B_REQUIRED,
	CASE_RULE_MFDS_DOMESTIC_INGREDIENTCODE_REQUIRED,
	CASE_RULE_MFDS_DOMESTIC_PRODUCTCODE_REQUIRED,
	CASE_RULE_MFDS_FOREIGN_WHOMPID_RECOMMENDED, CASE_RULE_MFDS_GK21_KR1A_REQUIRED,
	CASE_RULE_MFDS_GK21_KR1B_REQUIRED, CASE_RULE_MFDS_GK23R1_KR1A_REQUIRED,
	CASE_RULE_MFDS_GK23R1_KR1B_REQUIRED, CASE_RULE_MFDS_GK9I2R1_REQUIRED,
	CASE_RULE_MFDS_GK9I2R2_KR1_REQUIRED, CASE_RULE_MFDS_GK9I2R3_KR1_REQUIRED,
	CASE_RULE_MFDS_GK9I2R3_KR2_REQUIRED,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RuleLayer {
	Xsd,
	Ich,
	Fda,
	Mfds,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RuleTestSpec {
	pub code: &'static str,
	pub layer: RuleLayer,
	pub profile: Option<ValidationProfile>,
	pub section: &'static str,
	pub field_path: &'static str,
}

pub const XSD_RULE_TEST_MATRIX: &[RuleTestSpec] = &[
	RuleTestSpec {
		code: "ICH.XML.ROOT.ITSVERSION.REQUIRED",
		layer: RuleLayer::Xsd,
		profile: None,
		section: "root",
		field_path: "$.MCCI_IN200100UV01.@ITSVersion",
	},
	RuleTestSpec {
		code: "ICH.XML.ROOT.SCHEMALOCATION.REQUIRED",
		layer: RuleLayer::Xsd,
		profile: None,
		section: "root",
		field_path: "$.MCCI_IN200100UV01.@xsi:schemaLocation",
	},
	RuleTestSpec {
		code: "ICH.XML.PLACEHOLDER.VALUE.FORBIDDEN",
		layer: RuleLayer::Xsd,
		profile: None,
		section: "global",
		field_path: "$..@*",
	},
];

pub const CASE_RULE_TEST_MATRIX: &[RuleTestSpec] = &[
	RuleTestSpec {
		code: CASE_RULE_ICH_C1_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "C",
		field_path: "safetyReportIdentification",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_N_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "N",
		field_path: "messageHeader",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_C11_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "C",
		field_path: "safetyReportIdentification.safetyReportId",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_C12_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "C",
		field_path: "safetyReportIdentification.transmissionDate",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_C13_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "C",
		field_path: "safetyReportIdentification.reportType",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_C14_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "C",
		field_path: "safetyReportIdentification.dateFirstReceivedFromSource",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_C15_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "C",
		field_path: "safetyReportIdentification.dateOfMostRecentInformation",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_C17_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "C",
		field_path: "safetyReportIdentification.fulfilExpeditedCriteria",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_C31_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "C",
		field_path: "senderInformation.senderType",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_C32_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "C",
		field_path: "senderInformation.organizationName",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_C2R4_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "C",
		field_path: "primarySources.0.qualification",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_D1_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "D",
		field_path: "patientInformation.patientInitials",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_FR2_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "F",
		field_path: "testResults.0.testName",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_EI11A_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "E",
		field_path: "reactions.0.primarySourceReaction",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_EI11B_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "E",
		field_path: "reactions.0.reactionLanguage",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_EI7_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "E",
		field_path: "reactions.0.reactionOutcome",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_GK1_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "G",
		field_path: "drugs.0.drugCharacterization",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_GK22_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "G",
		field_path: "drugs.0.medicinalProduct",
	},
	RuleTestSpec {
		code: CASE_RULE_ICH_H1_REQUIRED,
		layer: RuleLayer::Ich,
		profile: Some(ValidationProfile::Ich),
		section: "H",
		field_path: "narrative.caseNarrative",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_C171_REQUIRED,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "C",
		field_path: "safetyReportIdentification.localCriteriaReportType",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_C112_RECOMMENDED,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "C",
		field_path: "safetyReportIdentification.combinationProductReportIndicator",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_C112_REQUIRED,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "C",
		field_path: "safetyReportIdentification.combinationProductReportIndicator",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_C2R2_EMAIL_REQUIRED,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "C",
		field_path: "primarySources.0.reporterEmail",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_C55A_REQUIRED,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "C",
		field_path: "studyInformation.sponsorStudyNumber",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_C55B_REQUIRED,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "C",
		field_path: "studyInformation.sponsorStudyNumber",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_C56R_REQUIRED,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "C",
		field_path: "studyInformation.registrations.0.registrationNumber",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_GK1A_CONDITIONAL,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "G",
		field_path: "drugs.0.deviceCharacteristics.0.valueCode",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_GK12_REQUIRED,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "G",
		field_path: "drugs.0.deviceCharacteristics.0.valueCode",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_GK12R11_REQUIRED,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "G",
		field_path: "drugs.0.deviceCharacteristics.0.valueCode",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_GK12R3_REQUIRED,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "G",
		field_path: "drugs.0.deviceCharacteristics.0.valueCode",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_D11_REQUIRED,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "D",
		field_path: "patientInformation.raceCode",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_D12_REQUIRED,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "D",
		field_path: "patientInformation.ethnicityCode",
	},
	RuleTestSpec {
		code: CASE_RULE_FDA_EI32H_REQUIRED,
		layer: RuleLayer::Fda,
		profile: Some(ValidationProfile::Fda),
		section: "E",
		field_path: "reactions.0.requiredIntervention",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_C2R4_KR1_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "C",
		field_path: "primarySources.0.qualificationKr1",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_C31_KR1_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "C",
		field_path: "senderInformation.senderType",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_C54_KR1_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "C",
		field_path: "studyInformation.0.studyTypeReactionKr1",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_D8R1_KR1B_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "D",
		field_path: "patientInformation.pastDrugs.0.mpid",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_D8R1_KR1A_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "D",
		field_path: "patientInformation.pastDrugs.0.mpidVersion",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_D108R1_KR1B_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "D",
		field_path: "patientInformation.parents.0.pastDrugs.0.mpid",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_D108R1_KR1A_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "D",
		field_path: "patientInformation.parents.0.pastDrugs.0.mpidVersion",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_DOMESTIC_PRODUCTCODE_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "G",
		field_path: "drugs.0.mpid",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_FOREIGN_WHOMPID_RECOMMENDED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "G",
		field_path: "drugs.0.mpid",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_DOMESTIC_INGREDIENTCODE_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "G",
		field_path: "drugs.0.activeSubstances.0.substanceTermId",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_GK21_KR1B_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "G",
		field_path: "drugs.0.mpid",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_GK21_KR1A_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "G",
		field_path: "drugs.0.mpidVersion",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_GK23R1_KR1B_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "G",
		field_path: "drugs.0.activeSubstances.0.substanceTermId",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_GK23R1_KR1A_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "G",
		field_path: "drugs.0.activeSubstances.0.substanceTermIdVersion",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_GK9I2R2_KR1_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "G",
		field_path: "drugs.0.drugReactionAssessments.0.methodOfAssessment",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_GK9I2R3_KR1_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "G",
		field_path: "drugs.0.drugReactionAssessments.0.resultOfAssessment",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_GK9I2R3_KR2_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "G",
		field_path: "drugs.0.drugReactionAssessments.0.resultOfAssessmentKr2",
	},
	RuleTestSpec {
		code: CASE_RULE_MFDS_GK9I2R1_REQUIRED,
		layer: RuleLayer::Mfds,
		profile: Some(ValidationProfile::Mfds),
		section: "G",
		field_path: "drugs.0.drugReactionAssessments.0.sourceOfAssessment",
	},
];
