#!/usr/bin/env python3
"""Build db/bootstrap/11-fda-device-codes.sql from the NCI EVS CDRH terminology
subsets source file (registry/sources/fda-cdrh-ncit-subsets.txt).

Rerun this script only when the source file is refreshed. IMDRF codes encode
the Level 1/2/3 hierarchy directly via prefix length after the "IMDRF:"
prefix is stripped: 3 chars = Level 1, 5 chars = Level 2, 7 chars = Level 3.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "sources" / "fda-cdrh-ncit-subsets.txt"
OUTPUT = ROOT.parent / "db" / "bootstrap" / "11-fda-device-codes.sql"

SUBSET_NAME = "Medical Device Problem"
LIST_NAME = "device_problem_code"

HEADER = """-- FDA Hierarchical Code Lists (Device Problem Code)
-- Source: NCI EVS FDA-CDRH_NCIt_Subsets.txt (https://evs.nci.nih.gov/ftp1/FDA/CDRH/)
-- Generated by registry/tools/build_fda_device_codes.py -- do not hand-edit rows below.

CREATE TABLE fda_hierarchical_code_lists (
    id BIGSERIAL PRIMARY KEY,
    audit_id UUID NOT NULL DEFAULT gen_random_uuid(),
    list_name VARCHAR(50) NOT NULL,
    ncit_concept_code VARCHAR(20) NOT NULL,
    level1_term VARCHAR(200) NOT NULL,
    level2_term VARCHAR(200),
    level3_term VARCHAR(200),
    fda_code VARCHAR(20) NOT NULL,
    imdrf_code VARCHAR(20) NOT NULL,

    CONSTRAINT unique_fda_hierarchical_code UNIQUE (list_name, ncit_concept_code),
    CONSTRAINT unique_fda_hierarchical_code_audit_id UNIQUE (audit_id)
);

CREATE INDEX idx_fda_hierarchical_code_list_name ON fda_hierarchical_code_lists(list_name);
CREATE INDEX idx_fda_hierarchical_code_level1 ON fda_hierarchical_code_lists(level1_term);
CREATE INDEX idx_fda_hierarchical_code_level2 ON fda_hierarchical_code_lists(level2_term);
CREATE INDEX idx_fda_hierarchical_code_level3 ON fda_hierarchical_code_lists(level3_term);

INSERT INTO fda_hierarchical_code_lists
    (list_name, ncit_concept_code, level1_term, level2_term, level3_term, fda_code, imdrf_code)
VALUES
"""


def sql_str(value: str | None) -> str:
    """Render a Python string (or None) as a SQL literal."""
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def parse_source(text: str) -> list[dict[str, str]]:
    """Parse the tab-delimited NCI EVS subsets file into row dicts."""
    lines = text.splitlines()
    header = lines[0].split("\t")
    rows = []
    for line in lines[1:]:
        if not line.strip():
            continue
        values = line.split("\t")
        rows.append(dict(zip(header, values)))
    return rows


def derive_terms(rows: list[dict[str, str]]) -> list[dict[str, str | None]]:
    """Given rows already filtered to one CDRH subset, derive Level 1/2/3 terms
    from each row's IMDRF code prefix and return the fields needed per output row."""
    term_by_code: dict[str, str] = {}
    for row in rows:
        imdrf_full = row["IMDRF Code"].strip()
        code = imdrf_full.split(":", 1)[1] if ":" in imdrf_full else imdrf_full
        term_by_code[code] = row["CDRH Preferred Term"].strip()

    derived = []
    for row in rows:
        imdrf_full = row["IMDRF Code"].strip()
        code = imdrf_full.split(":", 1)[1] if ":" in imdrf_full else imdrf_full
        level1_term = term_by_code.get(code[:3], code[:3])
        level2_term = term_by_code.get(code[:5]) if len(code) >= 5 else None
        level3_term = row["CDRH Preferred Term"].strip() if len(code) >= 7 else None
        derived.append(
            {
                "ncit_concept_code": row["NCIt Concept Code"].strip(),
                "level1_term": level1_term,
                "level2_term": level2_term,
                "level3_term": level3_term,
                "fda_code": row["CDRH Source Code"].strip(),
                "imdrf_code": imdrf_full,
            }
        )
    return derived


def build_sql(source_text: str) -> str:
    rows = [r for r in parse_source(source_text) if r.get("CDRH Subset Name") == SUBSET_NAME]
    derived_rows = derive_terms(rows)

    value_lines = []
    for row in derived_rows:
        value_lines.append(
            "("
            + ", ".join(
                [
                    sql_str(LIST_NAME),
                    sql_str(row["ncit_concept_code"]),
                    sql_str(row["level1_term"]),
                    sql_str(row["level2_term"]),
                    sql_str(row["level3_term"]),
                    sql_str(row["fda_code"]),
                    sql_str(row["imdrf_code"]),
                ]
            )
            + ")"
        )

    return HEADER + ",\n".join(value_lines) + ";\n"


def main() -> None:
    source_text = SOURCE.read_text(encoding="utf-8")
    sql = build_sql(source_text)
    OUTPUT.write_text(sql, encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(sql.splitlines())} lines)")


if __name__ == "__main__":
    main()
