use super::{
	ActionPolicy, AuthorizationFactDefinition, Availability,
	BuiltInIdentityDefinition, EntitlementDefinition, GrantDefinition,
	LegacyGrantAlias, PolicyRegistry,
};
use serde::Serialize;
use sha2::{Digest, Sha256};
use std::fmt::{Display, Formatter, Write as _};

#[derive(Debug)]
pub enum ContractExportError {
	Serialize(serde_json::Error),
	TypescriptSymbolCollision {
		symbol: String,
		first_action: String,
		second_action: String,
	},
}

impl Display for ContractExportError {
	fn fmt(&self, formatter: &mut Formatter<'_>) -> std::fmt::Result {
		match self {
			Self::Serialize(error) => write!(
				formatter,
				"authorization contract serialization failed: {error}"
			),
			Self::TypescriptSymbolCollision {
				symbol,
				first_action,
				second_action,
			} => write!(
				formatter,
				"authorization actions {first_action:?} and {second_action:?} both render as TypeScript symbol {symbol:?}"
			),
		}
	}
}

impl std::error::Error for ContractExportError {}

impl From<serde_json::Error> for ContractExportError {
	fn from(error: serde_json::Error) -> Self {
		Self::Serialize(error)
	}
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PdfRolePrivilegeRow {
	pub grant_id: String,
	pub order: u16,
	pub menu: String,
	pub type_name: String,
	pub privilege: String,
	pub availability: Availability,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AuthorizationContractExport {
	pub canonical_json: String,
	pub catalog_hash: String,
	pub pdf_rows: Vec<PdfRolePrivilegeRow>,
	pub typescript: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct CanonicalRegistryContract {
	schema_version: u32,
	grants: Vec<GrantDefinition>,
	entitlements: Vec<EntitlementDefinition>,
	actions: Vec<ActionPolicy>,
	built_in_identities: Vec<BuiltInIdentityDefinition>,
	authorization_facts: Vec<AuthorizationFactDefinition>,
	legacy_grant_aliases: Vec<LegacyGrantAlias>,
}

pub fn export_contract(
	registry: &PolicyRegistry,
) -> Result<AuthorizationContractExport, ContractExportError> {
	let mut grants = registry.grants().cloned().collect::<Vec<_>>();
	for grant in &mut grants {
		grant.implied_grants.sort_unstable();
		grant.entitlements.sort_unstable();
		grant.assignable_role_classes.sort_unstable();
	}
	grants.sort_unstable_by(|left, right| left.id.cmp(&right.id));
	let mut entitlements = registry.entitlements().cloned().collect::<Vec<_>>();
	entitlements.sort_unstable_by(|left, right| left.id.cmp(&right.id));
	let mut actions = registry.actions().cloned().collect::<Vec<_>>();
	for action in &mut actions {
		action.entitlements.sort_unstable();
		action.allowed_identities.sort_unstable();
		action.scope_conditions.sort_unstable();
		action.context_conditions.sort_unstable();
	}
	actions.sort_unstable_by(|left, right| left.id.cmp(&right.id));
	let mut built_in_identities = registry.built_in_identities().to_vec();
	for identity in &mut built_in_identities {
		identity.grants.sort_unstable();
	}
	built_in_identities.sort_unstable_by_key(|identity| identity.id);
	let mut authorization_facts = registry.facts().cloned().collect::<Vec<_>>();
	for fact in &mut authorization_facts {
		fact.columns.sort_unstable();
	}
	authorization_facts.sort_unstable_by(|left, right| left.id.cmp(&right.id));
	let mut legacy_grant_aliases =
		registry.legacy_aliases().cloned().collect::<Vec<_>>();
	legacy_grant_aliases
		.sort_unstable_by(|left, right| left.legacy_id.cmp(&right.legacy_id));
	let canonical = CanonicalRegistryContract {
		schema_version: 1,
		grants,
		entitlements,
		actions,
		built_in_identities,
		authorization_facts,
		legacy_grant_aliases,
	};
	let canonical_json = serde_json::to_string(&canonical)?;
	let digest = Sha256::digest(canonical_json.as_bytes());
	let catalog_hash = digest
		.iter()
		.map(|byte| format!("{byte:02x}"))
		.collect::<String>();
	let mut pdf_rows = registry
		.grants()
		.map(|grant| PdfRolePrivilegeRow {
			grant_id: grant.id.to_string(),
			order: grant.pdf_order,
			menu: grant.pdf_menu.clone(),
			type_name: grant.pdf_type.clone(),
			privilege: grant.pdf_privilege.clone(),
			availability: grant.availability,
		})
		.collect::<Vec<_>>();
	pdf_rows.sort_unstable_by_key(|row| row.order);
	let typescript = render_typescript(registry, &pdf_rows, &catalog_hash)?;
	Ok(AuthorizationContractExport {
		canonical_json,
		catalog_hash,
		pdf_rows,
		typescript,
	})
}

fn render_typescript(
	registry: &PolicyRegistry,
	pdf_rows: &[PdfRolePrivilegeRow],
	catalog_hash: &str,
) -> Result<String, ContractExportError> {
	let mut output = String::from(
		"// @generated by the backend Policy Registry. Do not edit.\n\nexport const Action = {\n",
	);
	let mut symbols = std::collections::BTreeMap::new();
	for action in registry.actions() {
		let symbol = typescript_symbol(action.id.as_str());
		if let Some(first_action) =
			symbols.insert(symbol.clone(), action.id.to_string())
		{
			return Err(ContractExportError::TypescriptSymbolCollision {
				symbol,
				first_action,
				second_action: action.id.to_string(),
			});
		}
		let action_id = serde_json::to_string(action.id.as_str())?;
		output.push_str(&format!("  {}: {},\n", symbol, action_id));
	}
	output.push_str(
		"} as const;\n\nexport type ActionId = (typeof Action)[keyof typeof Action];\n\n",
	);
	output.push_str(
		"export type GrantAvailability = \"implemented\" | \"reserved\";\n\nexport interface PdfRolePrivilegeRow {\n  readonly grantId: string;\n  readonly order: number;\n  readonly menu: string;\n  readonly typeName: string;\n  readonly privilege: string;\n  readonly availability: GrantAvailability;\n}\n\n",
	);
	output.push_str("export const PDF_ROLE_PRIVILEGE_ROWS = [\n");
	for row in pdf_rows {
		output.push_str("  {\n");
		writeln!(
			output,
			"    grantId: {},",
			serde_json::to_string(&row.grant_id)?
		)
		.expect("writing to a String cannot fail");
		writeln!(output, "    order: {},", row.order)
			.expect("writing to a String cannot fail");
		writeln!(output, "    menu: {},", serde_json::to_string(&row.menu)?)
			.expect("writing to a String cannot fail");
		writeln!(
			output,
			"    typeName: {},",
			serde_json::to_string(&row.type_name)?
		)
		.expect("writing to a String cannot fail");
		writeln!(
			output,
			"    privilege: {},",
			serde_json::to_string(&row.privilege)?
		)
		.expect("writing to a String cannot fail");
		writeln!(
			output,
			"    availability: {},",
			serde_json::to_string(&row.availability)?
		)
		.expect("writing to a String cannot fail");
		output.push_str("  },\n");
	}
	output.push_str("] as const satisfies readonly PdfRolePrivilegeRow[];\n\n");
	output.push_str(&format!(
		"export const CATALOG_HASH =\n  {catalog_hash:?};\n"
	));
	Ok(output)
}

fn typescript_symbol(id: &str) -> String {
	id.split(|character: char| !character.is_ascii_alphanumeric())
		.filter(|segment| !segment.is_empty())
		.map(|segment| {
			let mut chars = segment.chars();
			let mut symbol = String::new();
			if let Some(first) = chars.next() {
				symbol.push(first.to_ascii_uppercase());
			}
			symbol.extend(chars);
			symbol
		})
		.collect()
}

#[cfg(test)]
mod tests {
	use super::*;
	use crate::authorization::*;

	#[test]
	fn action_ids_render_as_stable_typescript_symbols() {
		assert_eq!(typescript_symbol("case.review.toggle"), "CaseReviewToggle");
		assert_eq!(typescript_symbol("audit_log.list"), "AuditLogList");
	}

	#[test]
	fn exporter_rejects_colliding_typescript_symbols() {
		let action = |id: &str| ActionPolicyInput {
			id: id.to_string(),
			decision_stage: DecisionStage::SubjectOnly,
			entitlement_rule: EntitlementRule::AllOf,
			entitlements: vec![],
			allowed_identities: vec![],
			scope_conditions: vec![],
			context_conditions: vec![],
			audit_classification: AuditClassification::Read,
		};
		let registry = PolicyRegistryBuilder::new()
			.action(action("foo.bar_baz"))
			.action(action("foo_bar.baz"))
			.build()
			.unwrap();
		assert!(matches!(
			export_contract(&registry),
			Err(ContractExportError::TypescriptSymbolCollision { .. })
		));
	}

	#[test]
	fn canonical_hash_ignores_unordered_nested_input_order() {
		let build = |reversed: bool| {
			let ordered = |left: &str, right: &str| {
				if reversed {
					vec![right.to_string(), left.to_string()]
				} else {
					vec![left.to_string(), right.to_string()]
				}
			};
			let role_classes = if reversed {
				vec![RoleClass::OperationalBuiltIn, RoleClass::Custom]
			} else {
				vec![RoleClass::Custom, RoleClass::OperationalBuiltIn]
			};
			let allowed_identities = if reversed {
				vec![
					BuiltInIdentityKind::OperationalUser,
					BuiltInIdentityKind::PlatformAdministrator,
				]
			} else {
				vec![
					BuiltInIdentityKind::PlatformAdministrator,
					BuiltInIdentityKind::OperationalUser,
				]
			};
			let scope_conditions = if reversed {
				vec![
					ScopeCondition::AccessWindow,
					ScopeCondition::ActiveMembership,
				]
			} else {
				vec![
					ScopeCondition::ActiveMembership,
					ScopeCondition::AccessWindow,
				]
			};
			let context_conditions = if reversed {
				vec![
					ContextCondition::WithinPrincipalScope,
					ContextCondition::SameOrganization,
				]
			} else {
				vec![
					ContextCondition::SameOrganization,
					ContextCondition::WithinPrincipalScope,
				]
			};

			PolicyRegistryBuilder::new()
				.entitlement("sample.read")
				.entitlement("sample.update")
				.grant(GrantDefinitionInput {
					id: "sample.manage".to_string(),
					pdf_order: 1,
					pdf_menu: "SAMPLE".to_string(),
					pdf_type: "Sample".to_string(),
					pdf_privilege: "Edit".to_string(),
					availability: Availability::Implemented,
					implied_grants: vec![],
					entitlements: ordered("sample.read", "sample.update"),
					assignable_role_classes: role_classes,
				})
				.action(ActionPolicyInput {
					id: "sample.manage".to_string(),
					decision_stage: DecisionStage::ContextRequired(
						ContextKind::Existing(ResourceKind::Application),
					),
					entitlement_rule: EntitlementRule::AllOf,
					entitlements: ordered("sample.read", "sample.update"),
					allowed_identities,
					scope_conditions,
					context_conditions,
					audit_classification: AuditClassification::Mutation,
				})
				.identity(BuiltInIdentityInput {
					kind: BuiltInIdentityKind::OperationalUser,
					id: "00000000-0000-0000-0000-000000000201".to_string(),
					stable_key: "test-operational".to_string(),
					role_class: RoleClass::OperationalBuiltIn,
					grants: vec!["sample.manage".to_string()],
				})
				.fact(AuthorizationFactInput {
					id: "sample.scope".to_string(),
					table: "samples".to_string(),
					columns: ordered("organization_id", "scope_id"),
					invalidation_domain: InvalidationDomain::Organization,
				})
				.build()
				.unwrap()
		};

		let forward = export_contract(&build(false)).unwrap();
		let reversed = export_contract(&build(true)).unwrap();
		assert_eq!(forward.canonical_json, reversed.canonical_json);
		assert_eq!(forward.catalog_hash, reversed.catalog_hash);
	}
}
