use super::{PortableFieldBinding, PortableValueType};

macro_rules! binding {
	($section:literal, $path:literal, $request:literal, $type:ident, [$($code:literal),+ $(,)?]) => {
		PortableFieldBinding {
			section: $section,
			frontend_path: $path,
			request_path: $request,
			value_type: PortableValueType::$type,
			rule_codes: &[$($code),+],
			null_flavor_path: None,
		}
	};
}

pub(super) const BINDINGS: &[PortableFieldBinding] = &[
	binding!("DM", "patientInformation.patientInitials", "patientInitials", String, ["ICH.D.1.LENGTH.MAX", "ICH.D.1.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.gpMedicalRecordNumber", "gpMedicalRecordNumber", String, ["ICH.D.1.1.1.LENGTH.MAX", "ICH.D.1.1.1.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.specialistRecordNumber", "specialistRecordNumber", String, ["ICH.D.1.1.2.LENGTH.MAX", "ICH.D.1.1.2.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.hospitalRecordNumber", "hospitalRecordNumber", String, ["ICH.D.1.1.3.LENGTH.MAX", "ICH.D.1.1.3.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.investigationNumber", "investigationNumber", String, ["ICH.D.1.1.4.LENGTH.MAX", "ICH.D.1.1.4.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.patientBirthDate", "patientBirthDate", String, ["ICH.D.2.1.ALLOWED.VALUE", "ICH.D.2.1.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.patientAge.value", "patientAge.value", Number, ["ICH.D.2.2a.ALLOWED.VALUE", "ICH.D.2.2a.LENGTH.MAX"]),
	binding!("DM", "patientInformation.patientAge.unit", "patientAge.unit", String, ["ICH.D.2.2b.LENGTH.MAX"]),
	binding!("DM", "patientInformation.gestationPeriod.value", "gestationPeriod.value", Number, ["ICH.D.2.2.1a.ALLOWED.VALUE", "ICH.D.2.2.1a.LENGTH.MAX"]),
	binding!("DM", "patientInformation.gestationPeriod.unit", "gestationPeriod.unit", String, ["ICH.D.2.2.1b.LENGTH.MAX"]),
	binding!("DM", "patientInformation.patientAgeGroup", "patientAgeGroup", String, ["ICH.D.2.3.ALLOWED.VALUE", "ICH.D.2.3.LENGTH.MAX"]),
	binding!("DM", "patientInformation.patientWeight.value", "patientWeight.value", Number, ["ICH.D.3.ALLOWED.VALUE", "ICH.D.3.LENGTH.MAX"]),
	binding!("DM", "patientInformation.patientHeight.value", "patientHeight.value", Number, ["ICH.D.4.ALLOWED.VALUE", "ICH.D.4.LENGTH.MAX"]),
	binding!("DM", "patientInformation.patientSex", "patientSex", String, ["ICH.D.5.ALLOWED.VALUE", "ICH.D.5.LENGTH.MAX", "ICH.D.5.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.raceCode", "raceCode", String, ["FDA.D.11.r.1.LENGTH.MAX"]),
	binding!("DM", "patientInformation.ethnicityCode", "ethnicityCode", String, ["FDA.D.12.LENGTH.MAX"]),
	binding!("DM", "patientInformation.lastMenstrualPeriodDate", "lastMenstrualPeriodDate", String, ["ICH.D.6.ALLOWED.VALUE", "ICH.D.6.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.medicalHistoryEpisodes[].meddraVersion", "medicalHistoryEpisodes[].meddraVersion", String, ["ICH.D.7.1.r.1a.ALLOWED.VALUE", "ICH.D.7.1.r.1a.LENGTH.MAX"]),
	binding!("DM", "patientInformation.medicalHistoryEpisodes[].meddraCode", "medicalHistoryEpisodes[].meddraCode", String, ["ICH.D.7.1.r.1b.ALLOWED.VALUE", "ICH.D.7.1.r.1b.LENGTH.MAX"]),
	binding!("DM", "patientInformation.medicalHistoryEpisodes[].startDate", "medicalHistoryEpisodes[].startDate", String, ["ICH.D.7.1.r.2.ALLOWED.VALUE", "ICH.D.7.1.r.2.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.medicalHistoryEpisodes[].continuing", "medicalHistoryEpisodes[].continuing", Boolean, ["ICH.D.7.1.r.3.ALLOWED.VALUE", "ICH.D.7.1.r.3.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.medicalHistoryEpisodes[].endDate", "medicalHistoryEpisodes[].endDate", String, ["ICH.D.7.1.r.4.ALLOWED.VALUE", "ICH.D.7.1.r.4.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.medicalHistoryEpisodes[].comments", "medicalHistoryEpisodes[].comments", String, ["ICH.D.7.1.r.5.LENGTH.MAX"]),
	binding!("DM", "patientInformation.medicalHistoryEpisodes[].familyHistory", "medicalHistoryEpisodes[].familyHistory", Boolean, ["ICH.D.7.1.r.6.ALLOWED.VALUE"]),
	binding!("DM", "patientInformation.medicalHistoryText", "medicalHistoryText", String, ["ICH.D.7.2.LENGTH.MAX", "ICH.D.7.2.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.concomitantTherapies", "concomitantTherapies", Boolean, ["ICH.D.7.3.ALLOWED.VALUE"]),
	binding!("DM", "patientInformation.patientDeath.dateOfDeath", "patientDeath.dateOfDeath", String, ["ICH.D.9.1.ALLOWED.VALUE", "ICH.D.9.1.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.patientDeath.reportedCausesOfDeath[].meddraVersion", "patientDeath.reportedCausesOfDeath[].meddraVersion", String, ["ICH.D.9.2.r.1a.ALLOWED.VALUE", "ICH.D.9.2.r.1a.LENGTH.MAX"]),
	binding!("DM", "patientInformation.patientDeath.reportedCausesOfDeath[].meddraCode", "patientDeath.reportedCausesOfDeath[].meddraCode", String, ["ICH.D.9.2.r.1b.ALLOWED.VALUE", "ICH.D.9.2.r.1b.LENGTH.MAX"]),
	binding!("DM", "patientInformation.patientDeath.reportedCausesOfDeath[].causeText", "patientDeath.reportedCausesOfDeath[].causeText", String, ["ICH.D.9.2.r.2.LENGTH.MAX"]),
	binding!("DM", "patientInformation.patientDeath.autopsyPerformed", "patientDeath.autopsyPerformed", Boolean, ["ICH.D.9.3.ALLOWED.VALUE", "ICH.D.9.3.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.patientDeath.autopsyCausesOfDeath[].meddraVersion", "patientDeath.autopsyCausesOfDeath[].meddraVersion", String, ["ICH.D.9.4.r.1a.ALLOWED.VALUE", "ICH.D.9.4.r.1a.LENGTH.MAX"]),
	binding!("DM", "patientInformation.patientDeath.autopsyCausesOfDeath[].meddraCode", "patientDeath.autopsyCausesOfDeath[].meddraCode", String, ["ICH.D.9.4.r.1b.ALLOWED.VALUE", "ICH.D.9.4.r.1b.LENGTH.MAX"]),
	binding!("DM", "patientInformation.patientDeath.autopsyCausesOfDeath[].causeText", "patientDeath.autopsyCausesOfDeath[].causeText", String, ["ICH.D.9.4.r.2.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.parentIdentification", "parentInformation.parentIdentification", String, ["ICH.D.10.1.LENGTH.MAX", "ICH.D.10.1.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.parentInformation.parentBirthDate", "parentInformation.parentBirthDate", String, ["ICH.D.10.2.1.ALLOWED.VALUE", "ICH.D.10.2.1.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.parentInformation.parentAge.value", "parentInformation.parentAge.value", Number, ["ICH.D.10.2.2a.ALLOWED.VALUE", "ICH.D.10.2.2a.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.parentAge.unit", "parentInformation.parentAge.unit", String, ["ICH.D.10.2.2b.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.parentLastMenstrualPeriodDate", "parentInformation.parentLastMenstrualPeriodDate", String, ["ICH.D.10.3.ALLOWED.VALUE", "ICH.D.10.3.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.parentInformation.parentWeight.value", "parentInformation.parentWeight.value", Number, ["ICH.D.10.4.ALLOWED.VALUE", "ICH.D.10.4.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.parentHeight.value", "parentInformation.parentHeight.value", Number, ["ICH.D.10.5.ALLOWED.VALUE", "ICH.D.10.5.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.parentSex", "parentInformation.parentSex", String, ["ICH.D.10.6.ALLOWED.VALUE", "ICH.D.10.6.LENGTH.MAX", "ICH.D.10.6.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.parentInformation.medicalHistoryEpisodes[].meddraVersion", "parentInformation.medicalHistoryEpisodes[].meddraVersion", String, ["ICH.D.10.7.1.r.1a.ALLOWED.VALUE", "ICH.D.10.7.1.r.1a.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.medicalHistoryEpisodes[].meddraCode", "parentInformation.medicalHistoryEpisodes[].meddraCode", String, ["ICH.D.10.7.1.r.1b.ALLOWED.VALUE", "ICH.D.10.7.1.r.1b.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.medicalHistoryEpisodes[].startDate", "parentInformation.medicalHistoryEpisodes[].startDate", String, ["ICH.D.10.7.1.r.2.ALLOWED.VALUE", "ICH.D.10.7.1.r.2.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.parentInformation.medicalHistoryEpisodes[].continuing", "parentInformation.medicalHistoryEpisodes[].continuing", Boolean, ["ICH.D.10.7.1.r.3.ALLOWED.VALUE", "ICH.D.10.7.1.r.3.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.parentInformation.medicalHistoryEpisodes[].endDate", "parentInformation.medicalHistoryEpisodes[].endDate", String, ["ICH.D.10.7.1.r.4.ALLOWED.VALUE", "ICH.D.10.7.1.r.4.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.parentInformation.medicalHistoryEpisodes[].comments", "parentInformation.medicalHistoryEpisodes[].comments", String, ["ICH.D.10.7.1.r.5.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.medicalHistoryText", "parentInformation.medicalHistoryText", String, ["ICH.D.10.7.2.LENGTH.MAX"]),

	binding!("DH", "patientInformation.pastDrugHistory[].drugName", "drugName", String, ["ICH.D.8.r.1.LENGTH.MAX", "ICH.D.8.r.1.NULLFLAVOR.ALLOWED"]),
	binding!("DH", "patientInformation.pastDrugHistory[].mfdsMedicinalProductVersion", "mfdsMedicinalProductVersion", String, ["MFDS.D.8.r.1.KR.1a.LENGTH.MAX"]),
	binding!("DH", "patientInformation.pastDrugHistory[].mfdsMedicinalProductId", "mfdsMedicinalProductId", String, ["MFDS.D.8.r.1.KR.1b.LENGTH.MAX"]),
	binding!("DH", "patientInformation.pastDrugHistory[].mpidVersion", "mpidVersion", String, ["ICH.D.8.r.2a.LENGTH.MAX"]),
	binding!("DH", "patientInformation.pastDrugHistory[].mpid", "mpid", String, ["ICH.D.8.r.2b.LENGTH.MAX"]),
	binding!("DH", "patientInformation.pastDrugHistory[].phpidVersion", "phpidVersion", String, ["ICH.D.8.r.3a.LENGTH.MAX"]),
	binding!("DH", "patientInformation.pastDrugHistory[].phpid", "phpid", String, ["ICH.D.8.r.3b.LENGTH.MAX"]),
	binding!("DH", "patientInformation.pastDrugHistory[].startDate", "startDate", String, ["ICH.D.8.r.4.ALLOWED.VALUE", "ICH.D.8.r.4.NULLFLAVOR.ALLOWED"]),
	binding!("DH", "patientInformation.pastDrugHistory[].endDate", "endDate", String, ["ICH.D.8.r.5.ALLOWED.VALUE", "ICH.D.8.r.5.NULLFLAVOR.ALLOWED"]),
	binding!("DH", "patientInformation.pastDrugHistory[].indicationMeddraVersion", "indicationMeddraVersion", String, ["ICH.D.8.r.6a.ALLOWED.VALUE", "ICH.D.8.r.6a.LENGTH.MAX"]),
	binding!("DH", "patientInformation.pastDrugHistory[].indicationMeddraCode", "indicationMeddraCode", String, ["ICH.D.8.r.6b.ALLOWED.VALUE", "ICH.D.8.r.6b.LENGTH.MAX"]),
	binding!("DH", "patientInformation.pastDrugHistory[].reactionMeddraVersion", "reactionMeddraVersion", String, ["ICH.D.8.r.7a.ALLOWED.VALUE", "ICH.D.8.r.7a.LENGTH.MAX"]),
	binding!("DH", "patientInformation.pastDrugHistory[].reactionMeddraCode", "reactionMeddraCode", String, ["ICH.D.8.r.7b.ALLOWED.VALUE", "ICH.D.8.r.7b.LENGTH.MAX"]),

	binding!("DM", "patientInformation.parentInformation.pastDrugHistory[].drugName", "parentInformation.pastDrugHistory[].drugName", String, ["ICH.D.10.8.r.1.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.pastDrugHistory[].mfdsMedicinalProductVersion", "parentInformation.pastDrugHistory[].mfdsMedicinalProductVersion", String, ["MFDS.D.10.8.r.1.KR.1a.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.pastDrugHistory[].mfdsMedicinalProductId", "parentInformation.pastDrugHistory[].mfdsMedicinalProductId", String, ["MFDS.D.10.8.r.1.KR.1b.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.pastDrugHistory[].mpidVersion", "parentInformation.pastDrugHistory[].mpidVersion", String, ["ICH.D.10.8.r.2a.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.pastDrugHistory[].mpid", "parentInformation.pastDrugHistory[].mpid", String, ["ICH.D.10.8.r.2b.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.pastDrugHistory[].phpidVersion", "parentInformation.pastDrugHistory[].phpidVersion", String, ["ICH.D.10.8.r.3a.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.pastDrugHistory[].phpid", "parentInformation.pastDrugHistory[].phpid", String, ["ICH.D.10.8.r.3b.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.pastDrugHistory[].startDate", "parentInformation.pastDrugHistory[].startDate", String, ["ICH.D.10.8.r.4.ALLOWED.VALUE", "ICH.D.10.8.r.4.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.parentInformation.pastDrugHistory[].endDate", "parentInformation.pastDrugHistory[].endDate", String, ["ICH.D.10.8.r.5.ALLOWED.VALUE", "ICH.D.10.8.r.5.NULLFLAVOR.ALLOWED"]),
	binding!("DM", "patientInformation.parentInformation.pastDrugHistory[].indicationMeddraVersion", "parentInformation.pastDrugHistory[].indicationMeddraVersion", String, ["ICH.D.10.8.r.6a.ALLOWED.VALUE", "ICH.D.10.8.r.6a.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.pastDrugHistory[].indicationMeddraCode", "parentInformation.pastDrugHistory[].indicationMeddraCode", String, ["ICH.D.10.8.r.6b.ALLOWED.VALUE", "ICH.D.10.8.r.6b.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.pastDrugHistory[].reactionMeddraVersion", "parentInformation.pastDrugHistory[].reactionMeddraVersion", String, ["ICH.D.10.8.r.7a.ALLOWED.VALUE", "ICH.D.10.8.r.7a.LENGTH.MAX"]),
	binding!("DM", "patientInformation.parentInformation.pastDrugHistory[].reactionMeddraCode", "parentInformation.pastDrugHistory[].reactionMeddraCode", String, ["ICH.D.10.8.r.7b.ALLOWED.VALUE", "ICH.D.10.8.r.7b.LENGTH.MAX"]),
];
