use super::{PortableFieldBinding, PortableValueType};

macro_rules! binding {
	($path:literal, $request:literal, $type:ident, [$($code:literal),+ $(,)?]) => {
		PortableFieldBinding {
			section: "DG",
			frontend_path: $path,
			request_path: $request,
			value_type: PortableValueType::$type,
			rule_codes: &[$($code),+],
			null_flavor_path: None,
		}
	};
	($path:literal, $request:literal, $type:ident, [$($code:literal),+ $(,)?], null: $null:literal) => {
		PortableFieldBinding {
			section: "DG",
			frontend_path: $path,
			request_path: $request,
			value_type: PortableValueType::$type,
			rule_codes: &[$($code),+],
			null_flavor_path: Some($null),
		}
	};
}

pub(super) const BINDINGS: &[PortableFieldBinding] = &[
	binding!(
		"drugs[].drugCharacterization",
		"drugCharacterization",
		String,
		["ICH.G.k.1.ALLOWED.VALUE", "ICH.G.k.1.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaOtherCharacterization",
		"fdaOtherCharacterization",
		String,
		["FDA.G.k.1.a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].mpidVersion",
		"mpidVersion",
		String,
		["ICH.G.k.2.1.1a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].mpid",
		"mpid",
		String,
		["ICH.G.k.2.1.1b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].phpidVersion",
		"phpidVersion",
		String,
		["ICH.G.k.2.1.2a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].phpid",
		"phpid",
		String,
		["ICH.G.k.2.1.2b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].mfdsMpidVersion",
		"mfdsMpidVersion",
		String,
		["MFDS.G.k.2.1.KR.1a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].mfdsMpid",
		"mfdsMpid",
		String,
		["MFDS.G.k.2.1.KR.1b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].medicinalProduct",
		"medicinalProduct",
		String,
		["ICH.G.k.2.2.LENGTH.MAX"]
	),
	binding!(
		"drugs[].obtainDrugCountry",
		"obtainDrugCountry",
		String,
		["ICH.G.k.2.4.LENGTH.MAX"]
	),
	binding!(
		"drugs[].investigationalProductBlinded",
		"investigationalProductBlinded",
		Boolean,
		["ICH.G.k.2.5.ALLOWED.VALUE"]
	),
	binding!(
		"drugs[].drugAuthorizationNumber",
		"drugAuthorizationNumber",
		String,
		["ICH.G.k.3.1.LENGTH.MAX"]
	),
	binding!(
		"drugs[].drugAuthorizationCountry",
		"drugAuthorizationCountry",
		String,
		["ICH.G.k.3.2.LENGTH.MAX"]
	),
	binding!(
		"drugs[].drugAuthorizationHolder",
		"drugAuthorizationHolder",
		String,
		["ICH.G.k.3.3.LENGTH.MAX"]
	),
	binding!(
		"drugs[].cumulativeDoseValue",
		"cumulativeDoseValue",
		Number,
		["ICH.G.k.5a.ALLOWED.VALUE", "ICH.G.k.5a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].cumulativeDoseUnit",
		"cumulativeDoseUnit",
		String,
		["ICH.G.k.5b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].gestationPeriodExposureValue",
		"gestationPeriodExposureValue",
		Number,
		["ICH.G.k.6a.ALLOWED.VALUE", "ICH.G.k.6a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].gestationPeriodExposureUnit",
		"gestationPeriodExposureUnit",
		String,
		["ICH.G.k.6b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].drugActionTaken",
		"drugActionTaken",
		String,
		["ICH.G.k.8.ALLOWED.VALUE", "ICH.G.k.8.LENGTH.MAX"]
	),
	binding!(
		"drugs[].drugAdditionalInformationCodes[]",
		"drugAdditionalInformationCodes[]",
		String,
		["ICH.G.k.10.r.ALLOWED.VALUE", "ICH.G.k.10.r.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaAdditionalInfoCoded",
		"fdaAdditionalInfoCoded",
		String,
		["FDA.G.k.10a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaSpecializedProductCategory",
		"fdaSpecializedProductCategory",
		String,
		["FDA.G.k.10.1.LENGTH.MAX"]
	),
	binding!(
		"drugs[].drugAdditionalInformation",
		"drugAdditionalInformation",
		String,
		["ICH.G.k.11.LENGTH.MAX"]
	),
	binding!(
		"drugs[].activeSubstances[].substanceName",
		"activeSubstances[].substanceName",
		String,
		["ICH.G.k.2.3.r.1.LENGTH.MAX"]
	),
	binding!(
		"drugs[].activeSubstances[].mfdsVersion",
		"activeSubstances[].mfdsVersion",
		String,
		["MFDS.G.k.2.3.r.1.KR.1a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].activeSubstances[].mfdsId",
		"activeSubstances[].mfdsId",
		String,
		["MFDS.G.k.2.3.r.1.KR.1b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].activeSubstances[].substanceTermIdVersion",
		"activeSubstances[].substanceTermIdVersion",
		String,
		["ICH.G.k.2.3.r.2a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].activeSubstances[].substanceTermId",
		"activeSubstances[].substanceTermId",
		String,
		["ICH.G.k.2.3.r.2b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].activeSubstances[].substanceStrengthValue",
		"activeSubstances[].substanceStrengthValue",
		Number,
		[
			"ICH.G.k.2.3.r.3a.ALLOWED.VALUE",
			"ICH.G.k.2.3.r.3a.LENGTH.MAX"
		]
	),
	binding!(
		"drugs[].activeSubstances[].substanceStrengthUnit",
		"activeSubstances[].substanceStrengthUnit",
		String,
		["ICH.G.k.2.3.r.3b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].dosageInformation[].doseValue",
		"dosageInformation[].doseValue",
		Number,
		["ICH.G.k.4.r.1a.ALLOWED.VALUE", "ICH.G.k.4.r.1a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].dosageInformation[].doseUnit",
		"dosageInformation[].doseUnit",
		String,
		["ICH.G.k.4.r.1b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].dosageInformation[].numberOfUnits",
		"dosageInformation[].numberOfUnits",
		Number,
		["ICH.G.k.4.r.2.ALLOWED.VALUE", "ICH.G.k.4.r.2.LENGTH.MAX"]
	),
	binding!(
		"drugs[].dosageInformation[].frequencyUnit",
		"dosageInformation[].frequencyUnit",
		String,
		["ICH.G.k.4.r.3.LENGTH.MAX"]
	),
	binding!("drugs[].dosageInformation[].firstAdministrationDate", "dosageInformation[].firstAdministrationDate", String, ["ICH.G.k.4.r.4.NULLFLAVOR.ALLOWED"], null: "drugs[].dosageInformation[].firstAdministrationDate"),
	binding!("drugs[].dosageInformation[].lastAdministrationDate", "dosageInformation[].lastAdministrationDate", String, ["ICH.G.k.4.r.5.NULLFLAVOR.ALLOWED"], null: "drugs[].dosageInformation[].lastAdministrationDate"),
	binding!(
		"drugs[].dosageInformation[].durationValue",
		"dosageInformation[].durationValue",
		Number,
		["ICH.G.k.4.r.6a.ALLOWED.VALUE", "ICH.G.k.4.r.6a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].dosageInformation[].durationUnit",
		"dosageInformation[].durationUnit",
		String,
		["ICH.G.k.4.r.6b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].dosageInformation[].batchNumber",
		"dosageInformation[].batchNumber",
		String,
		["ICH.G.k.4.r.7.LENGTH.MAX"]
	),
	binding!(
		"drugs[].dosageInformation[].dosageText",
		"dosageInformation[].dosageText",
		String,
		["ICH.G.k.4.r.8.LENGTH.MAX"]
	),
	binding!(
		"drugs[].dosageInformation[].doseForm",
		"dosageInformation[].doseForm",
		String,
		[
			"ICH.G.k.4.r.9.1.LENGTH.MAX",
			"ICH.G.k.4.r.9.1.NULLFLAVOR.ALLOWED"
		]
	),
	binding!(
		"drugs[].dosageInformation[].doseFormTermIdVersion",
		"dosageInformation[].doseFormTermIdVersion",
		String,
		["ICH.G.k.4.r.9.2a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].dosageInformation[].doseFormTermId",
		"dosageInformation[].doseFormTermId",
		String,
		["ICH.G.k.4.r.9.2b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].dosageInformation[].routeOfAdministration",
		"dosageInformation[].routeOfAdministration",
		String,
		[
			"ICH.G.k.4.r.10.1.LENGTH.MAX",
			"ICH.G.k.4.r.10.1.NULLFLAVOR.ALLOWED"
		]
	),
	binding!(
		"drugs[].dosageInformation[].routeTermIdVersion",
		"dosageInformation[].routeTermIdVersion",
		String,
		["ICH.G.k.4.r.10.2a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].dosageInformation[].routeTermId",
		"dosageInformation[].routeTermId",
		String,
		["ICH.G.k.4.r.10.2b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].dosageInformation[].parentRouteOfAdministration",
		"dosageInformation[].parentRouteOfAdministration",
		String,
		[
			"ICH.G.k.4.r.11.1.LENGTH.MAX",
			"ICH.G.k.4.r.11.1.NULLFLAVOR.ALLOWED"
		]
	),
	binding!(
		"drugs[].dosageInformation[].parentRouteTermIdVersion",
		"dosageInformation[].parentRouteTermIdVersion",
		String,
		["ICH.G.k.4.r.11.2a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].dosageInformation[].parentRouteTermId",
		"dosageInformation[].parentRouteTermId",
		String,
		["ICH.G.k.4.r.11.2b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].indications[].indicationText",
		"indications[].indicationText",
		String,
		[
			"ICH.G.k.7.r.1.LENGTH.MAX",
			"ICH.G.k.7.r.1.NULLFLAVOR.ALLOWED"
		]
	),
	binding!(
		"drugs[].indications[].indicationMeddraVersion",
		"indications[].indicationMeddraVersion",
		String,
		["ICH.G.k.7.r.2a.ALLOWED.VALUE", "ICH.G.k.7.r.2a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].indications[].indicationMeddraCode",
		"indications[].indicationMeddraCode",
		String,
		["ICH.G.k.7.r.2b.ALLOWED.VALUE", "ICH.G.k.7.r.2b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].drugReactionAssessments[].administrationStartIntervalValue",
		"drugReactionAssessments[].administrationStartIntervalValue",
		Number,
		[
			"ICH.G.k.9.i.3.1a.ALLOWED.VALUE",
			"ICH.G.k.9.i.3.1a.LENGTH.MAX"
		]
	),
	binding!(
		"drugs[].drugReactionAssessments[].administrationStartIntervalUnit",
		"drugReactionAssessments[].administrationStartIntervalUnit",
		String,
		["ICH.G.k.9.i.3.1b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].drugReactionAssessments[].lastDoseIntervalValue",
		"drugReactionAssessments[].lastDoseIntervalValue",
		Number,
		[
			"ICH.G.k.9.i.3.2a.ALLOWED.VALUE",
			"ICH.G.k.9.i.3.2a.LENGTH.MAX"
		]
	),
	binding!(
		"drugs[].drugReactionAssessments[].lastDoseIntervalUnit",
		"drugReactionAssessments[].lastDoseIntervalUnit",
		String,
		["ICH.G.k.9.i.3.2b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].drugReactionAssessments[].sourceOfAssessment",
		"drugReactionAssessments[].sourceOfAssessment",
		String,
		["ICH.G.k.9.i.2.r.1.LENGTH.MAX"]
	),
	binding!(
		"drugs[].drugReactionAssessments[].methodOfAssessment",
		"drugReactionAssessments[].methodOfAssessment",
		String,
		["ICH.G.k.9.i.2.r.2.LENGTH.MAX"]
	),
	binding!(
		"drugs[].drugReactionAssessments[].resultOfAssessment",
		"drugReactionAssessments[].resultOfAssessment",
		String,
		["ICH.G.k.9.i.2.r.3.LENGTH.MAX"]
	),
	binding!(
		"drugs[].drugReactionAssessments[].resultOfAssessmentKr2",
		"drugReactionAssessments[].resultOfAssessmentKr2",
		String,
		["MFDS.G.k.9.i.2.r.3.KR.2.LENGTH.MAX"]
	),
	binding!(
		"drugs[].drugReactionAssessments[].recurrenceAction",
		"drugReactionAssessments[].recurrenceAction",
		String,
		["ICH.G.k.9.i.4.ALLOWED.VALUE", "ICH.G.k.9.i.4.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.followUpTypes[].valueCode",
		"fdaDeviceInfo.followUpTypes[].valueCode",
		String,
		["FDA.G.k.12.r.2.r.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.deviceProblemCodes[].valueCode",
		"fdaDeviceInfo.deviceProblemCodes[].valueCode",
		String,
		["FDA.G.k.12.r.3.r.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.deviceBrandName",
		"fdaDeviceInfo.deviceBrandName",
		String,
		["FDA.G.k.12.r.4.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.commonDeviceName",
		"fdaDeviceInfo.commonDeviceName",
		String,
		["FDA.G.k.12.r.5.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.deviceProductCode",
		"fdaDeviceInfo.deviceProductCode",
		String,
		["FDA.G.k.12.r.6.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.manufacturerName",
		"fdaDeviceInfo.manufacturerName",
		String,
		["FDA.G.k.12.r.7.1a.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.manufacturerAddress",
		"fdaDeviceInfo.manufacturerAddress",
		String,
		["FDA.G.k.12.r.7.1b.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.manufacturerCity",
		"fdaDeviceInfo.manufacturerCity",
		String,
		["FDA.G.k.12.r.7.1c.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.manufacturerState",
		"fdaDeviceInfo.manufacturerState",
		String,
		["FDA.G.k.12.r.7.1d.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.manufacturerCountry",
		"fdaDeviceInfo.manufacturerCountry",
		String,
		["FDA.G.k.12.r.7.1e.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.deviceUsage",
		"fdaDeviceInfo.deviceUsage",
		String,
		["FDA.G.k.12.r.8.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.deviceLotNumber",
		"fdaDeviceInfo.deviceLotNumber",
		String,
		["FDA.G.k.12.r.9.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.operatorOfDevice",
		"fdaDeviceInfo.operatorOfDevice",
		String,
		["FDA.G.k.12.r.10.LENGTH.MAX"]
	),
	binding!(
		"drugs[].fdaDeviceInfo.remedialActions[].valueCode",
		"fdaDeviceInfo.remedialActions[].valueCode",
		String,
		["FDA.G.k.12.r.11.r.LENGTH.MAX"]
	),
];
