use axum::routing::get;
use axum::Router;
use lib_core::model::ModelManager;

use crate::web::rest::section_presave_rest;

/// Routes for relational INFO section presaves.
pub fn routes_section_presaves(mm: ModelManager) -> Router {
	Router::new()
		.route(
			"/presaves/senders",
			get(section_presave_rest::list_sender_presaves)
				.post(section_presave_rest::create_sender_presave),
		)
		.route(
			"/presaves/senders/{id}",
			get(section_presave_rest::get_sender_presave)
				.patch(section_presave_rest::update_sender_presave)
				.delete(section_presave_rest::delete_sender_presave),
		)
		.route(
			"/presaves/senders/{id}/details",
			get(section_presave_rest::get_sender_presave_details)
				.put(section_presave_rest::update_sender_presave_details),
		)
		.route(
			"/presaves/senders/{sender_id}/gateways",
			get(section_presave_rest::list_sender_gateways)
				.post(section_presave_rest::create_sender_gateway_from_path),
		)
		.route(
			"/presaves/senders/{sender_id}/gateways/{id}",
			get(section_presave_rest::get_sender_gateway)
				.patch(section_presave_rest::update_sender_gateway)
				.delete(section_presave_rest::delete_sender_gateway),
		)
		.route(
			"/presaves/senders/{sender_id}/responsible-persons",
			get(section_presave_rest::list_sender_responsible_persons)
				.post(section_presave_rest::create_sender_responsible_person),
		)
		.route(
			"/presaves/senders/{sender_id}/responsible-persons/{id}",
			get(section_presave_rest::get_sender_responsible_person)
				.patch(section_presave_rest::update_sender_responsible_person)
				.delete(section_presave_rest::delete_sender_responsible_person),
		)
		.route(
			"/presaves/receivers",
			get(section_presave_rest::list_receiver_presaves)
				.post(section_presave_rest::create_receiver_presave),
		)
		.route(
			"/presaves/receivers/{id}",
			get(section_presave_rest::get_receiver_presave)
				.patch(section_presave_rest::update_receiver_presave)
				.delete(section_presave_rest::delete_receiver_presave),
		)
		.route(
			"/presaves/receivers/{id}/details",
			get(section_presave_rest::get_receiver_presave_details)
				.put(section_presave_rest::update_receiver_presave_details),
		)
		.route(
			"/presaves/receivers/{receiver_id}/consignees",
			get(section_presave_rest::list_receiver_consignees)
				.post(section_presave_rest::create_receiver_consignee),
		)
		.route(
			"/presaves/receivers/{receiver_id}/consignees/{id}",
			get(section_presave_rest::get_receiver_consignee)
				.patch(section_presave_rest::update_receiver_consignee)
				.delete(section_presave_rest::delete_receiver_consignee),
		)
		.route(
			"/presaves/products",
			get(section_presave_rest::list_product_presaves)
				.post(section_presave_rest::create_product_presave),
		)
		.route(
			"/presaves/products/{id}",
			get(section_presave_rest::get_product_presave)
				.patch(section_presave_rest::update_product_presave)
				.delete(section_presave_rest::delete_product_presave),
		)
		.route(
			"/presaves/products/{id}/details",
			get(section_presave_rest::get_product_presave_details)
				.put(section_presave_rest::update_product_presave_details),
		)
		.route(
			"/presaves/products/{product_id}/substances",
			get(section_presave_rest::list_product_substances)
				.post(section_presave_rest::create_product_substance),
		)
		.route(
			"/presaves/products/{product_id}/substances/{id}",
			get(section_presave_rest::get_product_substance)
				.patch(section_presave_rest::update_product_substance)
				.delete(section_presave_rest::delete_product_substance),
		)
		.route(
			"/presaves/reporters",
			get(section_presave_rest::list_reporter_presaves)
				.post(section_presave_rest::create_reporter_presave),
		)
		.route(
			"/presaves/reporters/{id}",
			get(section_presave_rest::get_reporter_presave)
				.patch(section_presave_rest::update_reporter_presave)
				.delete(section_presave_rest::delete_reporter_presave),
		)
		.route(
			"/presaves/studies",
			get(section_presave_rest::list_study_presaves)
				.post(section_presave_rest::create_study_presave),
		)
		.route(
			"/presaves/studies/{id}",
			get(section_presave_rest::get_study_presave)
				.patch(section_presave_rest::update_study_presave)
				.delete(section_presave_rest::delete_study_presave),
		)
		.route(
			"/presaves/studies/{id}/details",
			get(section_presave_rest::get_study_presave_details)
				.put(section_presave_rest::update_study_presave_details),
		)
		.route(
			"/presaves/studies/{study_id}/registration-numbers",
			get(section_presave_rest::list_study_registration_numbers)
				.post(section_presave_rest::create_study_registration_number),
		)
		.route(
			"/presaves/studies/{study_id}/registration-numbers/{id}",
			get(section_presave_rest::get_study_registration_number)
				.patch(section_presave_rest::update_study_registration_number)
				.delete(section_presave_rest::delete_study_registration_number),
		)
		.route(
			"/presaves/studies/{study_id}/products",
			get(section_presave_rest::list_study_products)
				.post(section_presave_rest::create_study_product),
		)
		.route(
			"/presaves/studies/{study_id}/products/{id}",
			get(section_presave_rest::get_study_product)
				.patch(section_presave_rest::update_study_product)
				.delete(section_presave_rest::delete_study_product),
		)
		.route(
			"/presaves/studies/{study_id}/reporters",
			get(section_presave_rest::list_study_reporters)
				.post(section_presave_rest::create_study_reporter),
		)
		.route(
			"/presaves/studies/{study_id}/reporters/{id}",
			get(section_presave_rest::get_study_reporter)
				.patch(section_presave_rest::update_study_reporter)
				.delete(section_presave_rest::delete_study_reporter),
		)
		.route(
			"/presaves/narratives",
			get(section_presave_rest::list_narrative_presaves)
				.post(section_presave_rest::create_narrative_presave),
		)
		.route(
			"/presaves/narratives/{id}",
			get(section_presave_rest::get_narrative_presave)
				.patch(section_presave_rest::update_narrative_presave)
				.delete(section_presave_rest::delete_narrative_presave),
		)
		.with_state(mm)
}
