// Generated once from the former backend field bindings. Explicit calls are the maintained source.

use super::{validate_field, violation, InputType};
use input_contracts::{FieldInput, InputIssue};
use lib_rest_core::Result;
use serde_json::{Map, Value};
use std::collections::BTreeSet;

#[cfg(test)]
#[test]
fn draft_assessment_selections_allow_clear_but_reject_unknown_codes() {
	use input_contracts::InputValue;
	for value in [
		InputValue::Missing,
		InputValue::Null,
		InputValue::String(""),
	] {
		assert!(cioms_dechallenge_result(FieldInput::new(value, None)).is_empty());
		assert!(assessment_expectedness(FieldInput::new(value, None)).is_empty());
	}
	assert!(!cioms_dechallenge_result(FieldInput::new(
		InputValue::String("4"),
		None
	))
	.is_empty());
	assert!(!assessment_expectedness(FieldInput::new(
		InputValue::String("3"),
		None
	))
	.is_empty());
}

fn cioms_dechallenge_result(input: FieldInput<'_>) -> Vec<InputIssue> {
	let valid = match input.value {
		input_contracts::InputValue::Missing | input_contracts::InputValue::Null => {
			true
		}
		input_contracts::InputValue::String(value) => {
			matches!(value.trim(), "" | "1" | "2" | "3")
		}
		_ => false,
	};
	if valid {
		Vec::new()
	} else {
		vec![InputIssue {
			code: "CIOMS.ITEM20.ALLOWED.VALUE",
			message: "must be one of: 1, 2, 3".to_string(),
		}]
	}
}

fn assessment_expectedness(input: FieldInput<'_>) -> Vec<InputIssue> {
	let valid = match input.value {
		input_contracts::InputValue::Missing | input_contracts::InputValue::Null => {
			true
		}
		input_contracts::InputValue::String(value) => {
			matches!(value.trim(), "" | "1" | "2")
		}
		_ => false,
	};
	if valid {
		Vec::new()
	} else {
		vec![InputIssue {
			code: "LOCAL.G.k.9.i.expectedness.ALLOWED.VALUE",
			message: "must be one of: 1, 2".to_string(),
		}]
	}
}

pub(super) fn validate_section_fields(
	section: &str,
	row: &Map<String, Value>,
	changed_paths: Option<&BTreeSet<String>>,
	outer_indexes: &[usize],
	fda: bool,
) -> Result<()> {
	match section {
		"AE" => ae(row, changed_paths, outer_indexes),
		"CI" => ci(row, changed_paths, outer_indexes),
		"DG" => dg(row, changed_paths, outer_indexes),
		"DH" => dh(row, changed_paths, outer_indexes),
		"DM" => dm(row, changed_paths, outer_indexes, fda),
		"LB" => lb(row, changed_paths, outer_indexes),
		"LR" => lr(row, changed_paths, outer_indexes),
		"N" => n(row, changed_paths, outer_indexes),
		"NR" => nr(row, changed_paths, outer_indexes),
		"RP" => rp(row, changed_paths, outer_indexes),
		"SD" => sd(row, changed_paths, outer_indexes),
		"SI" => si(row, changed_paths, outer_indexes),
		_ => Ok(()),
	}
}

fn ae(
	row: &Map<String, Value>,
	changed_paths: Option<&BTreeSet<String>>,
	outer_indexes: &[usize],
) -> Result<()> {
	validate_field(
		row,
		"medicalConfirmation",
		"reactions[].medicalConfirmation",
		InputType::Boolean,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_8,
	)?;
	validate_field(
		row,
		"primarySourceReaction",
		"reactions[].primarySourceReaction",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_1_1a,
	)?;
	validate_field(
		row,
		"primarySourceReactionTranslation",
		"reactions[].primarySourceReactionTranslation",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_1_2,
	)?;
	validate_field(
		row,
		"reactionCountry",
		"reactions[].reactionCountry",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_9,
	)?;
	validate_field(
		row,
		"reactionDuration.unit",
		"reactions[].reactionDuration.unit",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_6b,
	)?;
	validate_field(
		row,
		"reactionDuration.value",
		"reactions[].reactionDuration.value",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_6a,
	)?;
	validate_field(
		row,
		"reactionEndDate",
		"reactions[].reactionEndDate",
		InputType::String,
		Some((
			"reactionEndDateNullFlavor",
			"reactions[].reactionEndDateNullFlavor",
			"ICH.E.i.5.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_5,
	)?;
	validate_field(
		row,
		"reactionLanguage",
		"reactions[].reactionLanguage",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_1_1b,
	)?;
	validate_field(
		row,
		"reactionMeddraCodeLLT",
		"reactions[].reactionMeddraCodeLLT",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_2_1b,
	)?;
	validate_field(
		row,
		"reactionMeddraVersionLLT",
		"reactions[].reactionMeddraVersionLLT",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_2_1a,
	)?;
	validate_field(
		row,
		"reactionOutcome",
		"reactions[].reactionOutcome",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_7,
	)?;
	validate_field(
		row,
		"reactionStartDate",
		"reactions[].reactionStartDate",
		InputType::String,
		Some((
			"reactionStartDateNullFlavor",
			"reactions[].reactionStartDateNullFlavor",
			"ICH.E.i.4.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_4,
	)?;
	validate_field(
		row,
		"requiredIntervention",
		"reactions[].requiredIntervention",
		InputType::Boolean,
		Some((
			"requiredInterventionNullFlavor",
			"reactions[].requiredInterventionNullFlavor",
			"FDA.E.i.3.2h.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::fda_e_i_3_2h,
	)?;
	validate_field(
		row,
		"seriousness.criteriaCongenitalAnomaly",
		"reactions[].seriousness.criteriaCongenitalAnomaly",
		InputType::Boolean,
		Some((
			"seriousness.criteriaCongenitalAnomalyNullFlavor",
			"reactions[].seriousness.criteriaCongenitalAnomalyNullFlavor",
			"ICH.E.i.3.2e.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_3_2e,
	)?;
	validate_field(
		row,
		"seriousness.criteriaDisabling",
		"reactions[].seriousness.criteriaDisabling",
		InputType::Boolean,
		Some((
			"seriousness.criteriaDisablingNullFlavor",
			"reactions[].seriousness.criteriaDisablingNullFlavor",
			"ICH.E.i.3.2d.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_3_2d,
	)?;
	validate_field(
		row,
		"seriousness.criteriaHospitalization",
		"reactions[].seriousness.criteriaHospitalization",
		InputType::Boolean,
		Some((
			"seriousness.criteriaHospitalizationNullFlavor",
			"reactions[].seriousness.criteriaHospitalizationNullFlavor",
			"ICH.E.i.3.2c.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_3_2c,
	)?;
	validate_field(
		row,
		"seriousness.criteriaLifeThreatening",
		"reactions[].seriousness.criteriaLifeThreatening",
		InputType::Boolean,
		Some((
			"seriousness.criteriaLifeThreateningNullFlavor",
			"reactions[].seriousness.criteriaLifeThreateningNullFlavor",
			"ICH.E.i.3.2b.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_3_2b,
	)?;
	validate_field(
		row,
		"seriousness.criteriaOtherMedicallyImportant",
		"reactions[].seriousness.criteriaOtherMedicallyImportant",
		InputType::Boolean,
		Some((
			"seriousness.criteriaOtherMedicallyImportantNullFlavor",
			"reactions[].seriousness.criteriaOtherMedicallyImportantNullFlavor",
			"ICH.E.i.3.2f.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_3_2f,
	)?;
	validate_field(
		row,
		"seriousness.criteriaResultsInDeath",
		"reactions[].seriousness.criteriaResultsInDeath",
		InputType::Boolean,
		Some((
			"seriousness.criteriaResultsInDeathNullFlavor",
			"reactions[].seriousness.criteriaResultsInDeathNullFlavor",
			"ICH.E.i.3.2a.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_3_2a,
	)?;
	validate_field(
		row,
		"termHighlighted",
		"reactions[].termHighlighted",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::e::e_i_3_1,
	)?;
	Ok(())
}

fn ci(
	row: &Map<String, Value>,
	changed_paths: Option<&BTreeSet<String>>,
	outer_indexes: &[usize],
) -> Result<()> {
	validate_field(
		row,
		"documentsHeldBySender[].documentDescription",
		"documentsHeldBySender[].documentDescription",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_6_1_r_1,
	)?;
	validate_field(
		row,
		"documentsHeldBySender[].includedDocument",
		"documentsHeldBySender[].includedDocument",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_6_1_r_2,
	)?;
	validate_field(
		row,
		"linkedReports[].linkedReportNumber",
		"linkedReports[].linkedReportNumber",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_10_r,
	)?;
	validate_field(
		row,
		"otherCaseIdentifiers[].caseIdentifier",
		"otherCaseIdentifiers[].caseIdentifier",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_9_1_r_2,
	)?;
	validate_field(
		row,
		"otherCaseIdentifiers[].source",
		"otherCaseIdentifiers[].source",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_9_1_r_1,
	)?;
	validate_field(
		row,
		"additionalDocumentsAvailable",
		"safetyReportIdentification.additionalDocumentsAvailable",
		InputType::Boolean,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_6_1,
	)?;
	validate_field(
		row,
		"combinationProductReportIndicator",
		"safetyReportIdentification.combinationProductReportIndicator",
		InputType::String,
		Some((
			"combinationProductReportIndicatorNullFlavor",
			"safetyReportIdentification.combinationProductReportIndicatorNullFlavor",
			"FDA.C.1.12.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::fda_c_1_12,
	)?;
	validate_field(
		row,
		"dateFirstReceivedFromSource",
		"safetyReportIdentification.dateFirstReceivedFromSource",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_4,
	)?;
	validate_field(
		row,
		"dateOfMostRecentInformation",
		"safetyReportIdentification.dateOfMostRecentInformation",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_5,
	)?;
	validate_field(
		row,
		"firstSenderType",
		"safetyReportIdentification.firstSenderType",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_8_2,
	)?;
	validate_field(
		row,
		"fulfilExpeditedCriteria",
		"safetyReportIdentification.fulfilExpeditedCriteria",
		InputType::Boolean,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_7,
	)?;
	validate_field(
		row,
		"localCriteriaReportType",
		"safetyReportIdentification.localCriteriaReportType",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::fda_c_1_7_1,
	)?;
	validate_field(
		row,
		"nullificationAmendmentCode",
		"safetyReportIdentification.nullificationAmendmentCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_11_1,
	)?;
	validate_field(
		row,
		"nullificationReason",
		"safetyReportIdentification.nullificationReason",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_11_2,
	)?;
	validate_field(
		row,
		"otherCaseIdentifiersExist",
		"safetyReportIdentification.otherCaseIdentifiersExist",
		InputType::Boolean,
		Some((
			"otherCaseIdentifiersExistNullFlavor",
			"safetyReportIdentification.otherCaseIdentifiersExistNullFlavor",
			"ICH.C.1.9.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_9_1,
	)?;
	validate_field(
		row,
		"reportType",
		"safetyReportIdentification.reportType",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_3,
	)?;
	validate_field(
		row,
		"safetyReportId",
		"safetyReportIdentification.safetyReportId",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_1,
	)?;
	validate_field(
		row,
		"transmissionDate",
		"safetyReportIdentification.transmissionDate",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_2,
	)?;
	validate_field(
		row,
		"worldwideUniqueId",
		"safetyReportIdentification.worldwideUniqueId",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_1_8_1,
	)?;
	Ok(())
}

fn dg(
	row: &Map<String, Value>,
	changed_paths: Option<&BTreeSet<String>>,
	outer_indexes: &[usize],
) -> Result<()> {
	super::validate_local_text(
		row,
		"drugBatchNumber",
		"drugs[].drugBatchNumber",
		35,
	)?;
	validate_field(
		row,
		"activeSubstances[].mfdsId",
		"drugs[].activeSubstances[].mfdsId",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::mfds_g_k_2_3_r_1_kr_1b,
	)?;
	validate_field(
		row,
		"activeSubstances[].mfdsVersion",
		"drugs[].activeSubstances[].mfdsVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::mfds_g_k_2_3_r_1_kr_1a,
	)?;
	validate_field(
		row,
		"activeSubstances[].substanceName",
		"drugs[].activeSubstances[].substanceName",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_2_3_r_1,
	)?;
	validate_field(
		row,
		"activeSubstances[].substanceStrengthUnit",
		"drugs[].activeSubstances[].substanceStrengthUnit",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_2_3_r_3b,
	)?;
	validate_field(
		row,
		"activeSubstances[].substanceStrengthValue",
		"drugs[].activeSubstances[].substanceStrengthValue",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_2_3_r_3a,
	)?;
	validate_field(
		row,
		"activeSubstances[].substanceTermId",
		"drugs[].activeSubstances[].substanceTermId",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_2_3_r_2b,
	)?;
	validate_field(
		row,
		"activeSubstances[].substanceTermIdVersion",
		"drugs[].activeSubstances[].substanceTermIdVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_2_3_r_2a,
	)?;
	validate_field(
		row,
		"cumulativeDoseUnit",
		"drugs[].cumulativeDoseUnit",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_5b,
	)?;
	validate_field(
		row,
		"cumulativeDoseValue",
		"drugs[].cumulativeDoseValue",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_5a,
	)?;
	validate_field(
		row,
		"dosageInformation[].batchNumber",
		"drugs[].dosageInformation[].batchNumber",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_7,
	)?;
	validate_field(
		row,
		"dosageInformation[].dosageText",
		"drugs[].dosageInformation[].dosageText",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_8,
	)?;
	validate_field(
		row,
		"dosageInformation[].doseForm",
		"drugs[].dosageInformation[].doseForm",
		InputType::String,
		Some((
			"dosageInformation[].doseFormNullFlavor",
			"drugs[].dosageInformation[].doseFormNullFlavor",
			"ICH.G.k.4.r.9.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_9_1,
	)?;
	validate_field(
		row,
		"dosageInformation[].doseFormTermId",
		"drugs[].dosageInformation[].doseFormTermId",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_9_2b,
	)?;
	validate_field(
		row,
		"dosageInformation[].doseFormTermIdVersion",
		"drugs[].dosageInformation[].doseFormTermIdVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_9_2a,
	)?;
	validate_field(
		row,
		"dosageInformation[].doseUnit",
		"drugs[].dosageInformation[].doseUnit",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_1b,
	)?;
	validate_field(
		row,
		"dosageInformation[].doseValue",
		"drugs[].dosageInformation[].doseValue",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_1a,
	)?;
	validate_field(
		row,
		"dosageInformation[].durationUnit",
		"drugs[].dosageInformation[].durationUnit",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_6b,
	)?;
	validate_field(
		row,
		"dosageInformation[].durationValue",
		"drugs[].dosageInformation[].durationValue",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_6a,
	)?;
	validate_field(
		row,
		"dosageInformation[].firstAdministrationDate",
		"drugs[].dosageInformation[].firstAdministrationDate",
		InputType::String,
		Some((
			"dosageInformation[].firstAdministrationDateNullFlavor",
			"drugs[].dosageInformation[].firstAdministrationDateNullFlavor",
			"ICH.G.k.4.r.4.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_4,
	)?;
	validate_field(
		row,
		"dosageInformation[].frequencyUnit",
		"drugs[].dosageInformation[].frequencyUnit",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_3,
	)?;
	validate_field(
		row,
		"dosageInformation[].lastAdministrationDate",
		"drugs[].dosageInformation[].lastAdministrationDate",
		InputType::String,
		Some((
			"dosageInformation[].lastAdministrationDateNullFlavor",
			"drugs[].dosageInformation[].lastAdministrationDateNullFlavor",
			"ICH.G.k.4.r.5.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_5,
	)?;
	validate_field(
		row,
		"dosageInformation[].numberOfUnits",
		"drugs[].dosageInformation[].numberOfUnits",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_2,
	)?;
	validate_field(
		row,
		"dosageInformation[].parentRouteOfAdministration",
		"drugs[].dosageInformation[].parentRouteOfAdministration",
		InputType::String,
		Some((
			"dosageInformation[].parentRouteOfAdministrationNullFlavor",
			"drugs[].dosageInformation[].parentRouteOfAdministrationNullFlavor",
			"ICH.G.k.4.r.11.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_11_1,
	)?;
	validate_field(
		row,
		"dosageInformation[].parentRouteTermId",
		"drugs[].dosageInformation[].parentRouteTermId",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_11_2b,
	)?;
	validate_field(
		row,
		"dosageInformation[].parentRouteTermIdVersion",
		"drugs[].dosageInformation[].parentRouteTermIdVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_11_2a,
	)?;
	validate_field(
		row,
		"dosageInformation[].routeOfAdministration",
		"drugs[].dosageInformation[].routeOfAdministration",
		InputType::String,
		Some((
			"dosageInformation[].routeOfAdministrationNullFlavor",
			"drugs[].dosageInformation[].routeOfAdministrationNullFlavor",
			"ICH.G.k.4.r.10.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_10_1,
	)?;
	validate_field(
		row,
		"dosageInformation[].routeTermId",
		"drugs[].dosageInformation[].routeTermId",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_10_2b,
	)?;
	validate_field(
		row,
		"dosageInformation[].routeTermIdVersion",
		"drugs[].dosageInformation[].routeTermIdVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_4_r_10_2a,
	)?;
	validate_field(
		row,
		"drugActionTaken",
		"drugs[].drugActionTaken",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_8,
	)?;
	validate_field(
		row,
		"drugAdditionalInformation",
		"drugs[].drugAdditionalInformation",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_11,
	)?;
	validate_field(
		row,
		"drugAdditionalInformationCodes[]",
		"drugs[].drugAdditionalInformationCodes[]",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_10_r,
	)?;
	validate_field(
		row,
		"drugAuthorizationCountry",
		"drugs[].drugAuthorizationCountry",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_3_2,
	)?;
	validate_field(
		row,
		"drugAuthorizationHolder",
		"drugs[].drugAuthorizationHolder",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_3_3,
	)?;
	validate_field(
		row,
		"drugAuthorizationNumber",
		"drugs[].drugAuthorizationNumber",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_3_1,
	)?;
	validate_field(
		row,
		"drugCharacterization",
		"drugs[].drugCharacterization",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_1,
	)?;
	validate_field(
		row,
		"drugReactionAssessments[].administrationStartIntervalUnit",
		"drugs[].drugReactionAssessments[].administrationStartIntervalUnit",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_9_i_3_1b,
	)?;
	validate_field(
		row,
		"drugReactionAssessments[].administrationStartIntervalValue",
		"drugs[].drugReactionAssessments[].administrationStartIntervalValue",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_9_i_3_1a,
	)?;
	validate_field(
		row,
		"drugReactionAssessments[].lastDoseIntervalUnit",
		"drugs[].drugReactionAssessments[].lastDoseIntervalUnit",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_9_i_3_2b,
	)?;
	validate_field(
		row,
		"drugReactionAssessments[].lastDoseIntervalValue",
		"drugs[].drugReactionAssessments[].lastDoseIntervalValue",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_9_i_3_2a,
	)?;
	validate_field(
		row,
		"drugReactionAssessments[].methodOfAssessment",
		"drugs[].drugReactionAssessments[].methodOfAssessment",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_9_i_2_r_2,
	)?;
	validate_field(
		row,
		"drugReactionAssessments[].methodOfAssessmentKr1",
		"drugs[].drugReactionAssessments[].methodOfAssessmentKr1",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::mfds_g_k_9_i_2_r_2_kr_1,
	)?;
	validate_field(
		row,
		"drugReactionAssessments[].recurrenceAction",
		"drugs[].drugReactionAssessments[].recurrenceAction",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_9_i_4,
	)?;
	validate_field(
		row,
		"drugReactionAssessments[].dechallengeResult",
		"drugs[].drugReactionAssessments[].dechallengeResult",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		cioms_dechallenge_result,
	)?;
	validate_field(
		row,
		"drugReactionAssessments[].expectedness",
		"drugs[].drugReactionAssessments[].expectedness",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		assessment_expectedness,
	)?;
	validate_field(
		row,
		"drugReactionAssessments[].resultOfAssessment",
		"drugs[].drugReactionAssessments[].resultOfAssessment",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_9_i_2_r_3,
	)?;
	validate_field(
		row,
		"drugReactionAssessments[].resultOfAssessmentKr1",
		"drugs[].drugReactionAssessments[].resultOfAssessmentKr1",
		InputType::String,
		Some((
			"drugReactionAssessments[].resultOfAssessmentKr1NullFlavor",
			"drugs[].drugReactionAssessments[].resultOfAssessmentKr1NullFlavor",
			"MFDS.G.k.9.i.2.r.3.KR.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::mfds_g_k_9_i_2_r_3_kr_1,
	)?;
	validate_field(
		row,
		"drugReactionAssessments[].resultOfAssessmentKr2",
		"drugs[].drugReactionAssessments[].resultOfAssessmentKr2",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::mfds_g_k_9_i_2_r_3_kr_2,
	)?;
	validate_field(
		row,
		"drugReactionAssessments[].sourceOfAssessment",
		"drugs[].drugReactionAssessments[].sourceOfAssessment",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_9_i_2_r_1,
	)?;
	validate_field(
		row,
		"fdaAdditionalInfoCoded",
		"drugs[].fdaAdditionalInfoCoded",
		InputType::String,
		Some((
			"fdaAdditionalInfoCodedNullFlavor",
			"drugs[].fdaAdditionalInfoCodedNullFlavor",
			"FDA.G.k.10a.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_10a,
	)?;
	validate_field(
		row,
		"fdaDevices[].commonDeviceName",
		"drugs[].fdaDevices[].commonDeviceName",
		InputType::String,
		Some((
			"fdaDevices[].commonDeviceNameNullFlavor",
			"drugs[].fdaDevices[].commonDeviceNameNullFlavor",
			"FDA.G.k.12.r.5.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_5,
	)?;
	validate_field(
		row,
		"fdaDevices[].deviceBrandName",
		"drugs[].fdaDevices[].deviceBrandName",
		InputType::String,
		Some((
			"fdaDevices[].deviceBrandNameNullFlavor",
			"drugs[].fdaDevices[].deviceBrandNameNullFlavor",
			"FDA.G.k.12.r.4.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_4,
	)?;
	validate_field(
		row,
		"fdaDevices[].deviceLotNumber",
		"drugs[].fdaDevices[].deviceLotNumber",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_9,
	)?;
	validate_field(
		row,
		"fdaDevices[].deviceProblemCodes[].valueCode",
		"drugs[].fdaDevices[].deviceProblemCodes[].valueCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_3_r,
	)?;
	validate_field(
		row,
		"fdaDevices[].deviceProductCode",
		"drugs[].fdaDevices[].deviceProductCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_6,
	)?;
	validate_field(
		row,
		"fdaDevices[].deviceUsage",
		"drugs[].fdaDevices[].deviceUsage",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_8,
	)?;
	validate_field(
		row,
		"fdaDevices[].followUpTypes[].valueCode",
		"drugs[].fdaDevices[].followUpTypes[].valueCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_2_r,
	)?;
	validate_field(
		row,
		"fdaDevices[].manufacturerAddress",
		"drugs[].fdaDevices[].manufacturerAddress",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_7_1b,
	)?;
	validate_field(
		row,
		"fdaDevices[].manufacturerCity",
		"drugs[].fdaDevices[].manufacturerCity",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_7_1c,
	)?;
	validate_field(
		row,
		"fdaDevices[].manufacturerCountry",
		"drugs[].fdaDevices[].manufacturerCountry",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_7_1e,
	)?;
	validate_field(
		row,
		"fdaDevices[].manufacturerName",
		"drugs[].fdaDevices[].manufacturerName",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_7_1a,
	)?;
	validate_field(
		row,
		"fdaDevices[].manufacturerState",
		"drugs[].fdaDevices[].manufacturerState",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_7_1d,
	)?;
	validate_field(
		row,
		"fdaDevices[].operatorOfDevice",
		"drugs[].fdaDevices[].operatorOfDevice",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_10,
	)?;
	validate_field(
		row,
		"fdaDevices[].remedialActions[].valueCode",
		"drugs[].fdaDevices[].remedialActions[].valueCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_12_r_11_r,
	)?;
	validate_field(
		row,
		"fdaOtherCharacterization",
		"drugs[].fdaOtherCharacterization",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_1_a,
	)?;
	validate_field(
		row,
		"fdaSpecializedProductCategory",
		"drugs[].fdaSpecializedProductCategory",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::fda_g_k_10_1,
	)?;
	validate_field(
		row,
		"gestationPeriodExposureUnit",
		"drugs[].gestationPeriodExposureUnit",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_6b,
	)?;
	validate_field(
		row,
		"gestationPeriodExposureValue",
		"drugs[].gestationPeriodExposureValue",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_6a,
	)?;
	validate_field(
		row,
		"indications[].indicationMeddraCode",
		"drugs[].indications[].indicationMeddraCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_7_r_2b,
	)?;
	validate_field(
		row,
		"indications[].indicationMeddraVersion",
		"drugs[].indications[].indicationMeddraVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_7_r_2a,
	)?;
	validate_field(
		row,
		"indications[].indicationText",
		"drugs[].indications[].indicationText",
		InputType::String,
		Some((
			"indications[].indicationTextNullFlavor",
			"drugs[].indications[].indicationTextNullFlavor",
			"ICH.G.k.7.r.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_7_r_1,
	)?;
	validate_field(
		row,
		"investigationalProductBlinded",
		"drugs[].investigationalProductBlinded",
		InputType::Boolean,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_2_5,
	)?;
	validate_field(
		row,
		"medicinalProduct",
		"drugs[].medicinalProduct",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_2_2,
	)?;
	validate_field(
		row,
		"mfdsMpid",
		"drugs[].mfdsMpid",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::mfds_g_k_2_1_kr_1b,
	)?;
	validate_field(
		row,
		"mfdsMpidVersion",
		"drugs[].mfdsMpidVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::mfds_g_k_2_1_kr_1a,
	)?;
	validate_field(
		row,
		"mpid",
		"drugs[].mpid",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_2_1_1b,
	)?;
	validate_field(
		row,
		"mpidVersion",
		"drugs[].mpidVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_2_1_1a,
	)?;
	validate_field(
		row,
		"obtainDrugCountry",
		"drugs[].obtainDrugCountry",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_2_4,
	)?;
	validate_field(
		row,
		"phpid",
		"drugs[].phpid",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_2_1_2b,
	)?;
	validate_field(
		row,
		"phpidVersion",
		"drugs[].phpidVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::g::g_k_2_1_2a,
	)?;
	Ok(())
}

fn dh(
	row: &Map<String, Value>,
	changed_paths: Option<&BTreeSet<String>>,
	outer_indexes: &[usize],
) -> Result<()> {
	validate_field(
		row,
		"drugName",
		"patientInformation.pastDrugHistory[].drugName",
		InputType::String,
		Some((
			"drugNameNullFlavor",
			"patientInformation.pastDrugHistory[].drugNameNullFlavor",
			"ICH.D.8.r.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_8_r_1,
	)?;
	validate_field(
		row,
		"endDate",
		"patientInformation.pastDrugHistory[].endDate",
		InputType::String,
		Some((
			"endDateNullFlavor",
			"patientInformation.pastDrugHistory[].endDateNullFlavor",
			"ICH.D.8.r.5.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_8_r_5,
	)?;
	validate_field(
		row,
		"indicationMeddraCode",
		"patientInformation.pastDrugHistory[].indicationMeddraCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_8_r_6b,
	)?;
	validate_field(
		row,
		"indicationMeddraVersion",
		"patientInformation.pastDrugHistory[].indicationMeddraVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_8_r_6a,
	)?;
	validate_field(
		row,
		"mfdsMedicinalProductId",
		"patientInformation.pastDrugHistory[].mfdsMedicinalProductId",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::mfds_d_8_r_1_kr_1b,
	)?;
	validate_field(
		row,
		"mfdsMedicinalProductVersion",
		"patientInformation.pastDrugHistory[].mfdsMedicinalProductVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::mfds_d_8_r_1_kr_1a,
	)?;
	validate_field(
		row,
		"mpid",
		"patientInformation.pastDrugHistory[].mpid",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_8_r_2b,
	)?;
	validate_field(
		row,
		"mpidVersion",
		"patientInformation.pastDrugHistory[].mpidVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_8_r_2a,
	)?;
	validate_field(
		row,
		"phpid",
		"patientInformation.pastDrugHistory[].phpid",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_8_r_3b,
	)?;
	validate_field(
		row,
		"phpidVersion",
		"patientInformation.pastDrugHistory[].phpidVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_8_r_3a,
	)?;
	validate_field(
		row,
		"reactionMeddraCode",
		"patientInformation.pastDrugHistory[].reactionMeddraCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_8_r_7b,
	)?;
	validate_field(
		row,
		"reactionMeddraVersion",
		"patientInformation.pastDrugHistory[].reactionMeddraVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_8_r_7a,
	)?;
	validate_field(
		row,
		"startDate",
		"patientInformation.pastDrugHistory[].startDate",
		InputType::String,
		Some((
			"startDateNullFlavor",
			"patientInformation.pastDrugHistory[].startDateNullFlavor",
			"ICH.D.8.r.4.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_8_r_4,
	)?;
	Ok(())
}

fn dm(
	row: &Map<String, Value>,
	changed_paths: Option<&BTreeSet<String>>,
	outer_indexes: &[usize],
	fda: bool,
) -> Result<()> {
	if fda
		&& row
			.get("raceCodes")
			.and_then(Value::as_array)
			.is_some_and(|values| {
				values.iter().any(|value| {
					value.as_str().is_some_and(|value| !value.trim().is_empty())
				})
			}) && row
		.get("raceCodeNullFlavor")
		.and_then(Value::as_str)
		.is_some_and(|value| !value.trim().is_empty())
	{
		return Err(violation(
			"FDA.D.11.r.1.NULLFLAVOR.ALLOWED",
			"patientInformation.raceCodeNullFlavor",
			"race codes and NullFlavor cannot both be set",
		));
	}
	validate_field(
		row,
		"concomitantTherapies",
		"patientInformation.concomitantTherapies",
		InputType::Boolean,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_7_3,
	)?;
	validate_field(
		row,
		"ethnicityCode",
		"patientInformation.ethnicityCode",
		InputType::String,
		Some((
			"ethnicityCodeNullFlavor",
			"patientInformation.ethnicityCodeNullFlavor",
			"FDA.D.12.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::fda_d_12,
	)?;
	validate_field(
		row,
		"gestationPeriod.unit",
		"patientInformation.gestationPeriod.unit",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_2_2_1b,
	)?;
	validate_field(
		row,
		"gestationPeriod.value",
		"patientInformation.gestationPeriod.value",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_2_2_1a,
	)?;
	validate_field(
		row,
		"gpMedicalRecordNumber",
		"patientInformation.gpMedicalRecordNumber",
		InputType::String,
		Some((
			"gpMedicalRecordNumberNullFlavor",
			"patientInformation.gpMedicalRecordNumberNullFlavor",
			"ICH.D.1.1.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_1_1_1,
	)?;
	validate_field(
		row,
		"hospitalRecordNumber",
		"patientInformation.hospitalRecordNumber",
		InputType::String,
		Some((
			"hospitalRecordNumberNullFlavor",
			"patientInformation.hospitalRecordNumberNullFlavor",
			"ICH.D.1.1.3.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_1_1_3,
	)?;
	validate_field(
		row,
		"investigationNumber",
		"patientInformation.investigationNumber",
		InputType::String,
		Some((
			"investigationNumberNullFlavor",
			"patientInformation.investigationNumberNullFlavor",
			"ICH.D.1.1.4.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_1_1_4,
	)?;
	validate_field(
		row,
		"lastMenstrualPeriodDate",
		"patientInformation.lastMenstrualPeriodDate",
		InputType::String,
		Some((
			"lastMenstrualPeriodDateNullFlavor",
			"patientInformation.lastMenstrualPeriodDateNullFlavor",
			"ICH.D.6.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_6,
	)?;
	validate_field(
		row,
		"medicalHistoryEpisodes[].comments",
		"patientInformation.medicalHistoryEpisodes[].comments",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_7_1_r_5,
	)?;
	validate_field(
		row,
		"medicalHistoryEpisodes[].continuing",
		"patientInformation.medicalHistoryEpisodes[].continuing",
		InputType::Boolean,
		Some((
			"medicalHistoryEpisodes[].continuingNullFlavor",
			"patientInformation.medicalHistoryEpisodes[].continuingNullFlavor",
			"ICH.D.7.1.r.3.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_7_1_r_3,
	)?;
	validate_field(
		row,
		"medicalHistoryEpisodes[].endDate",
		"patientInformation.medicalHistoryEpisodes[].endDate",
		InputType::String,
		Some((
			"medicalHistoryEpisodes[].endDateNullFlavor",
			"patientInformation.medicalHistoryEpisodes[].endDateNullFlavor",
			"ICH.D.7.1.r.4.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_7_1_r_4,
	)?;
	validate_field(
		row,
		"medicalHistoryEpisodes[].familyHistory",
		"patientInformation.medicalHistoryEpisodes[].familyHistory",
		InputType::Boolean,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_7_1_r_6,
	)?;
	validate_field(
		row,
		"medicalHistoryEpisodes[].meddraCode",
		"patientInformation.medicalHistoryEpisodes[].meddraCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_7_1_r_1b,
	)?;
	validate_field(
		row,
		"medicalHistoryEpisodes[].meddraVersion",
		"patientInformation.medicalHistoryEpisodes[].meddraVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_7_1_r_1a,
	)?;
	validate_field(
		row,
		"medicalHistoryEpisodes[].startDate",
		"patientInformation.medicalHistoryEpisodes[].startDate",
		InputType::String,
		Some((
			"medicalHistoryEpisodes[].startDateNullFlavor",
			"patientInformation.medicalHistoryEpisodes[].startDateNullFlavor",
			"ICH.D.7.1.r.2.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_7_1_r_2,
	)?;
	validate_field(
		row,
		"medicalHistoryText",
		"patientInformation.medicalHistoryText",
		InputType::String,
		Some((
			"medicalHistoryTextNullFlavor",
			"patientInformation.medicalHistoryTextNullFlavor",
			"ICH.D.7.2.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_7_2,
	)?;
	validate_field(
		row,
		"parentInformation.medicalHistoryEpisodes[].comments",
		"patientInformation.parentInformation.medicalHistoryEpisodes[].comments",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_7_1_r_5,
	)?;
	validate_field(
		row,
		"parentInformation.medicalHistoryEpisodes[].continuing",
		"patientInformation.parentInformation.medicalHistoryEpisodes[].continuing",
		InputType::Boolean,
		Some((
		"parentInformation.medicalHistoryEpisodes[].continuingNullFlavor",
		"patientInformation.parentInformation.medicalHistoryEpisodes[].continuingNullFlavor",
		"ICH.D.10.7.1.r.3.NULLFLAVOR.ALLOWED",
	)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_7_1_r_3,
	)?;
	validate_field(
		row,
		"parentInformation.medicalHistoryEpisodes[].endDate",
		"patientInformation.parentInformation.medicalHistoryEpisodes[].endDate",
		InputType::String,
		Some((
		"parentInformation.medicalHistoryEpisodes[].endDateNullFlavor",
		"patientInformation.parentInformation.medicalHistoryEpisodes[].endDateNullFlavor",
		"ICH.D.10.7.1.r.4.NULLFLAVOR.ALLOWED",
	)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_7_1_r_4,
	)?;
	validate_field(
		row,
		"parentInformation.medicalHistoryEpisodes[].meddraCode",
		"patientInformation.parentInformation.medicalHistoryEpisodes[].meddraCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_7_1_r_1b,
	)?;
	validate_field(
		row,
		"parentInformation.medicalHistoryEpisodes[].meddraVersion",
		"patientInformation.parentInformation.medicalHistoryEpisodes[].meddraVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_7_1_r_1a,
	)?;
	validate_field(
		row,
		"parentInformation.medicalHistoryEpisodes[].startDate",
		"patientInformation.parentInformation.medicalHistoryEpisodes[].startDate",
		InputType::String,
		Some((
		"parentInformation.medicalHistoryEpisodes[].startDateNullFlavor",
		"patientInformation.parentInformation.medicalHistoryEpisodes[].startDateNullFlavor",
		"ICH.D.10.7.1.r.2.NULLFLAVOR.ALLOWED",
	)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_7_1_r_2,
	)?;
	validate_field(
		row,
		"parentInformation.medicalHistoryText",
		"patientInformation.parentInformation.medicalHistoryText",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_7_2,
	)?;
	validate_field(
		row,
		"parentInformation.parentAge.unit",
		"patientInformation.parentInformation.parentAge.unit",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_2_2b,
	)?;
	validate_field(
		row,
		"parentInformation.parentAge.value",
		"patientInformation.parentInformation.parentAge.value",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_2_2a,
	)?;
	validate_field(
		row,
		"parentInformation.parentBirthDate",
		"patientInformation.parentInformation.parentBirthDate",
		InputType::String,
		Some((
			"parentInformation.parentBirthDateNullFlavor",
			"patientInformation.parentInformation.parentBirthDateNullFlavor",
			"ICH.D.10.2.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_2_1,
	)?;
	validate_field(
		row,
		"parentInformation.parentHeight.value",
		"patientInformation.parentInformation.parentHeight.value",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_5,
	)?;
	validate_field(
		row,
		"parentInformation.parentIdentification",
		"patientInformation.parentInformation.parentIdentification",
		InputType::String,
		Some((
			"parentInformation.parentIdentificationNullFlavor",
			"patientInformation.parentInformation.parentIdentificationNullFlavor",
			"ICH.D.10.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_1,
	)?;
	validate_field(
		row,
		"parentInformation.parentLastMenstrualPeriodDate",
		"patientInformation.parentInformation.parentLastMenstrualPeriodDate",
		InputType::String,
		Some((
		"parentInformation.parentLastMenstrualPeriodDateNullFlavor",
		"patientInformation.parentInformation.parentLastMenstrualPeriodDateNullFlavor",
		"ICH.D.10.3.NULLFLAVOR.ALLOWED",
	)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_3,
	)?;
	validate_field(
		row,
		"parentInformation.parentSex",
		"patientInformation.parentInformation.parentSex",
		InputType::String,
		Some((
			"parentInformation.parentSexNullFlavor",
			"patientInformation.parentInformation.parentSexNullFlavor",
			"ICH.D.10.6.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_6,
	)?;
	validate_field(
		row,
		"parentInformation.parentWeight.value",
		"patientInformation.parentInformation.parentWeight.value",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_4,
	)?;
	validate_field(
		row,
		"parentInformation.pastDrugHistory[].drugName",
		"patientInformation.parentInformation.pastDrugHistory[].drugName",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_8_r_1,
	)?;
	validate_field(
		row,
		"parentInformation.pastDrugHistory[].endDate",
		"patientInformation.parentInformation.pastDrugHistory[].endDate",
		InputType::String,
		Some((
		"parentInformation.pastDrugHistory[].endDateNullFlavor",
		"patientInformation.parentInformation.pastDrugHistory[].endDateNullFlavor",
		"ICH.D.10.8.r.5.NULLFLAVOR.ALLOWED",
	)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_8_r_5,
	)?;
	validate_field(
		row,
		"parentInformation.pastDrugHistory[].indicationMeddraCode",
		"patientInformation.parentInformation.pastDrugHistory[].indicationMeddraCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_8_r_6b,
	)?;
	validate_field(
		row,
		"parentInformation.pastDrugHistory[].indicationMeddraVersion",
		"patientInformation.parentInformation.pastDrugHistory[].indicationMeddraVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_8_r_6a,
	)?;
	validate_field(
		row,
		"parentInformation.pastDrugHistory[].mfdsMedicinalProductId",
		"patientInformation.parentInformation.pastDrugHistory[].mfdsMedicinalProductId",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::mfds_d_10_8_r_1_kr_1b,
	)?;
	validate_field(
		row,
		"parentInformation.pastDrugHistory[].mfdsMedicinalProductVersion",
		"patientInformation.parentInformation.pastDrugHistory[].mfdsMedicinalProductVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::mfds_d_10_8_r_1_kr_1a,
	)?;
	validate_field(
		row,
		"parentInformation.pastDrugHistory[].mpid",
		"patientInformation.parentInformation.pastDrugHistory[].mpid",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_8_r_2b,
	)?;
	validate_field(
		row,
		"parentInformation.pastDrugHistory[].mpidVersion",
		"patientInformation.parentInformation.pastDrugHistory[].mpidVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_8_r_2a,
	)?;
	validate_field(
		row,
		"parentInformation.pastDrugHistory[].phpid",
		"patientInformation.parentInformation.pastDrugHistory[].phpid",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_8_r_3b,
	)?;
	validate_field(
		row,
		"parentInformation.pastDrugHistory[].phpidVersion",
		"patientInformation.parentInformation.pastDrugHistory[].phpidVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_8_r_3a,
	)?;
	validate_field(
		row,
		"parentInformation.pastDrugHistory[].reactionMeddraCode",
		"patientInformation.parentInformation.pastDrugHistory[].reactionMeddraCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_8_r_7b,
	)?;
	validate_field(
		row,
		"parentInformation.pastDrugHistory[].reactionMeddraVersion",
		"patientInformation.parentInformation.pastDrugHistory[].reactionMeddraVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_8_r_7a,
	)?;
	validate_field(
		row,
		"parentInformation.pastDrugHistory[].startDate",
		"patientInformation.parentInformation.pastDrugHistory[].startDate",
		InputType::String,
		Some((
		"parentInformation.pastDrugHistory[].startDateNullFlavor",
		"patientInformation.parentInformation.pastDrugHistory[].startDateNullFlavor",
		"ICH.D.10.8.r.4.NULLFLAVOR.ALLOWED",
	)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_10_8_r_4,
	)?;
	validate_field(
		row,
		"patientAge.unit",
		"patientInformation.patientAge.unit",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_2_2b,
	)?;
	validate_field(
		row,
		"patientAge.value",
		"patientInformation.patientAge.value",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_2_2a,
	)?;
	validate_field(
		row,
		"patientAgeGroup",
		"patientInformation.patientAgeGroup",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_2_3,
	)?;
	validate_field(
		row,
		"patientBirthDate",
		"patientInformation.patientBirthDate",
		InputType::String,
		Some((
			"patientBirthDateNullFlavor",
			"patientInformation.patientBirthDateNullFlavor",
			"ICH.D.2.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_2_1,
	)?;
	validate_field(
		row,
		"patientDeath.autopsyCausesOfDeath[].causeText",
		"patientInformation.patientDeath.autopsyCausesOfDeath[].causeText",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_9_4_r_2,
	)?;
	validate_field(
		row,
		"patientDeath.autopsyCausesOfDeath[].meddraCode",
		"patientInformation.patientDeath.autopsyCausesOfDeath[].meddraCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_9_4_r_1b,
	)?;
	validate_field(
		row,
		"patientDeath.autopsyCausesOfDeath[].meddraVersion",
		"patientInformation.patientDeath.autopsyCausesOfDeath[].meddraVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_9_4_r_1a,
	)?;
	validate_field(
		row,
		"patientDeath.autopsyPerformed",
		"patientInformation.patientDeath.autopsyPerformed",
		InputType::Boolean,
		Some((
			"patientDeath.autopsyPerformedNullFlavor",
			"patientInformation.patientDeath.autopsyPerformedNullFlavor",
			"ICH.D.9.3.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_9_3,
	)?;
	validate_field(
		row,
		"patientDeath.dateOfDeath",
		"patientInformation.patientDeath.dateOfDeath",
		InputType::String,
		Some((
			"patientDeath.dateOfDeathNullFlavor",
			"patientInformation.patientDeath.dateOfDeathNullFlavor",
			"ICH.D.9.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_9_1,
	)?;
	validate_field(
		row,
		"patientDeath.reportedCausesOfDeath[].causeText",
		"patientInformation.patientDeath.reportedCausesOfDeath[].causeText",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_9_2_r_2,
	)?;
	validate_field(
		row,
		"patientDeath.reportedCausesOfDeath[].meddraCode",
		"patientInformation.patientDeath.reportedCausesOfDeath[].meddraCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_9_2_r_1b,
	)?;
	validate_field(
		row,
		"patientDeath.reportedCausesOfDeath[].meddraVersion",
		"patientInformation.patientDeath.reportedCausesOfDeath[].meddraVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_9_2_r_1a,
	)?;
	validate_field(
		row,
		"patientHeight.value",
		"patientInformation.patientHeight.value",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_4,
	)?;
	let (patient_initials_rule, patient_initials_check): (
		&str,
		fn(FieldInput<'_>) -> Vec<InputIssue>,
	) = if fda {
		(
			"FDA.D.1.NULLFLAVOR.ALLOWED",
			input_contracts::generated::d::fda_d_1,
		)
	} else {
		(
			"ICH.D.1.NULLFLAVOR.ALLOWED",
			input_contracts::generated::d::d_1,
		)
	};
	validate_field(
		row,
		"patientInitials",
		"patientInformation.patientInitials",
		InputType::String,
		Some((
			"patientInitialsNullFlavor",
			"patientInformation.patientInitialsNullFlavor",
			patient_initials_rule,
		)),
		changed_paths,
		outer_indexes,
		patient_initials_check,
	)?;
	validate_field(
		row,
		"patientSex",
		"patientInformation.patientSex",
		InputType::String,
		Some((
			"patientSexNullFlavor",
			"patientInformation.patientSexNullFlavor",
			"ICH.D.5.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_5,
	)?;
	validate_field(
		row,
		"patientWeight.value",
		"patientInformation.patientWeight.value",
		InputType::Number,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_3,
	)?;
	validate_field(
		row,
		"raceCodes[]",
		"patientInformation.raceCodes[]",
		InputType::String,
		Some((
			"raceCodeNullFlavor",
			"patientInformation.raceCodeNullFlavor",
			"FDA.D.11.r.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::fda_d_11_r_1,
	)?;
	validate_field(
		row,
		"specialistRecordNumber",
		"patientInformation.specialistRecordNumber",
		InputType::String,
		Some((
			"specialistRecordNumberNullFlavor",
			"patientInformation.specialistRecordNumberNullFlavor",
			"ICH.D.1.1.2.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::d::d_1_1_2,
	)?;
	Ok(())
}

fn lb(
	row: &Map<String, Value>,
	changed_paths: Option<&BTreeSet<String>>,
	outer_indexes: &[usize],
) -> Result<()> {
	validate_field(
		row,
		"comments",
		"testResults[].comments",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::f::f_r_6,
	)?;
	validate_field(
		row,
		"highRange",
		"testResults[].highRange",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::f::f_r_5,
	)?;
	validate_field(
		row,
		"lowRange",
		"testResults[].lowRange",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::f::f_r_4,
	)?;
	validate_field(
		row,
		"moreInformationAvailable",
		"testResults[].moreInformationAvailable",
		InputType::Boolean,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::f::f_r_7,
	)?;
	validate_field(
		row,
		"testDate",
		"testResults[].testDate",
		InputType::String,
		Some((
			"testDateNullFlavor",
			"testResults[].testDateNullFlavor",
			"ICH.F.r.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::f::f_r_1,
	)?;
	validate_field(
		row,
		"testMeddraCode",
		"testResults[].testMeddraCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::f::f_r_2_2b,
	)?;
	validate_field(
		row,
		"testMeddraVersion",
		"testResults[].testMeddraVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::f::f_r_2_2a,
	)?;
	validate_field(
		row,
		"testName",
		"testResults[].testName",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::f::f_r_2_1,
	)?;
	validate_field(
		row,
		"testResult",
		"testResults[].testResult",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::f::f_r_3_2,
	)?;
	validate_field(
		row,
		"testResultCode",
		"testResults[].testResultCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::f::f_r_3_1,
	)?;
	validate_field(
		row,
		"testResultUnstructured",
		"testResults[].testResultUnstructured",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::f::f_r_3_4,
	)?;
	validate_field(
		row,
		"testUnit",
		"testResults[].testUnit",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::f::f_r_3_3,
	)?;
	Ok(())
}

fn lr(
	row: &Map<String, Value>,
	changed_paths: Option<&BTreeSet<String>>,
	outer_indexes: &[usize],
) -> Result<()> {
	validate_field(
		row,
		"documentBase64",
		"literatureReferences[].documentBase64",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_4_r_2,
	)?;
	validate_field(
		row,
		"referenceText",
		"literatureReferences[].referenceText",
		InputType::String,
		Some((
			"referenceTextNullFlavor",
			"literatureReferences[].referenceTextNullFlavor",
			"ICH.C.4.r.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_4_r_1,
	)?;
	Ok(())
}

fn n(
	row: &Map<String, Value>,
	changed_paths: Option<&BTreeSet<String>>,
	outer_indexes: &[usize],
) -> Result<()> {
	validate_field(
		row,
		"batchNumber",
		"messageHeader.batchNumber",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::n::n_1_2,
	)?;
	validate_field(
		row,
		"batchReceiverIdentifier",
		"messageHeader.batchReceiverIdentifier",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::n::n_1_4,
	)?;
	validate_field(
		row,
		"batchSenderIdentifier",
		"messageHeader.batchSenderIdentifier",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::n::n_1_3,
	)?;
	validate_field(
		row,
		"batchTransmissionDate",
		"messageHeader.batchTransmissionDate",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::n::n_1_5,
	)?;
	validate_field(
		row,
		"messageDate",
		"messageHeader.messageDate",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::n::n_2_r_4,
	)?;
	validate_field(
		row,
		"messageNumber",
		"messageHeader.messageNumber",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::n::n_2_r_1,
	)?;
	validate_field(
		row,
		"messageReceiverIdentifier",
		"messageHeader.messageReceiverIdentifier",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::n::n_2_r_3,
	)?;
	validate_field(
		row,
		"messageSenderIdentifier",
		"messageHeader.messageSenderIdentifier",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::n::n_2_r_2,
	)?;
	validate_field(
		row,
		"messageType",
		"messageHeader.messageType",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::n::n_1_1,
	)?;
	Ok(())
}

fn nr(
	row: &Map<String, Value>,
	changed_paths: Option<&BTreeSet<String>>,
	outer_indexes: &[usize],
) -> Result<()> {
	validate_field(
		row,
		"caseSummaryInformation[].languageCode",
		"caseSummaryInformation[].languageCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::h::h_5_r_1b,
	)?;
	validate_field(
		row,
		"caseSummaryInformation[].summaryText",
		"caseSummaryInformation[].summaryText",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::h::h_5_r_1a,
	)?;
	validate_field(
		row,
		"caseNarrative",
		"narrative.caseNarrative",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::h::h_1,
	)?;
	validate_field(
		row,
		"reporterComments",
		"narrative.reporterComments",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::h::h_2,
	)?;
	validate_field(
		row,
		"senderComments",
		"narrative.senderComments",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::h::h_4,
	)?;
	validate_field(
		row,
		"senderDiagnoses[].diagnosisMeddraCode",
		"narrative.senderDiagnoses[].diagnosisMeddraCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::h::h_3_r_1b,
	)?;
	validate_field(
		row,
		"senderDiagnoses[].diagnosisMeddraVersion",
		"narrative.senderDiagnoses[].diagnosisMeddraVersion",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::h::h_3_r_1a,
	)?;
	Ok(())
}

fn rp(
	row: &Map<String, Value>,
	changed_paths: Option<&BTreeSet<String>>,
	outer_indexes: &[usize],
) -> Result<()> {
	validate_field(
		row,
		"primarySourceForRegulatoryPurposes",
		"primarySources[].primarySourceForRegulatoryPurposes",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_5,
	)?;
	validate_field(
		row,
		"qualification",
		"primarySources[].qualification",
		InputType::String,
		Some((
			"qualificationNullFlavor",
			"primarySources[].qualificationNullFlavor",
			"ICH.C.2.r.4.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_4,
	)?;
	validate_field(
		row,
		"qualificationKr1",
		"primarySources[].qualificationKr1",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::mfds_c_2_r_4_kr_1,
	)?;
	validate_field(
		row,
		"reporterCity",
		"primarySources[].reporterCity",
		InputType::String,
		Some((
			"reporterCityNullFlavor",
			"primarySources[].reporterCityNullFlavor",
			"ICH.C.2.r.2.4.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_2_4,
	)?;
	validate_field(
		row,
		"reporterCountry",
		"primarySources[].reporterCountry",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_3,
	)?;
	validate_field(
		row,
		"reporterDepartment",
		"primarySources[].reporterDepartment",
		InputType::String,
		Some((
			"reporterDepartmentNullFlavor",
			"primarySources[].reporterDepartmentNullFlavor",
			"ICH.C.2.r.2.2.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_2_2,
	)?;
	validate_field(
		row,
		"reporterEmail",
		"primarySources[].reporterEmail",
		InputType::String,
		Some((
			"reporterEmailNullFlavor",
			"primarySources[].reporterEmailNullFlavor",
			"FDA.C.2.r.2.8.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::fda_c_2_r_2_8,
	)?;
	validate_field(
		row,
		"reporterFamilyName",
		"primarySources[].reporterFamilyName",
		InputType::String,
		Some((
			"reporterFamilyNameNullFlavor",
			"primarySources[].reporterFamilyNameNullFlavor",
			"ICH.C.2.r.1.4.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_1_4,
	)?;
	validate_field(
		row,
		"reporterGivenName",
		"primarySources[].reporterGivenName",
		InputType::String,
		Some((
			"reporterGivenNameNullFlavor",
			"primarySources[].reporterGivenNameNullFlavor",
			"ICH.C.2.r.1.2.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_1_2,
	)?;
	validate_field(
		row,
		"reporterMiddleName",
		"primarySources[].reporterMiddleName",
		InputType::String,
		Some((
			"reporterMiddleNameNullFlavor",
			"primarySources[].reporterMiddleNameNullFlavor",
			"ICH.C.2.r.1.3.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_1_3,
	)?;
	validate_field(
		row,
		"reporterOrganization",
		"primarySources[].reporterOrganization",
		InputType::String,
		Some((
			"reporterOrganizationNullFlavor",
			"primarySources[].reporterOrganizationNullFlavor",
			"ICH.C.2.r.2.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_2_1,
	)?;
	validate_field(
		row,
		"reporterPostcode",
		"primarySources[].reporterPostcode",
		InputType::String,
		Some((
			"reporterPostcodeNullFlavor",
			"primarySources[].reporterPostcodeNullFlavor",
			"ICH.C.2.r.2.6.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_2_6,
	)?;
	validate_field(
		row,
		"reporterState",
		"primarySources[].reporterState",
		InputType::String,
		Some((
			"reporterStateNullFlavor",
			"primarySources[].reporterStateNullFlavor",
			"ICH.C.2.r.2.5.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_2_5,
	)?;
	validate_field(
		row,
		"reporterStreet",
		"primarySources[].reporterStreet",
		InputType::String,
		Some((
			"reporterStreetNullFlavor",
			"primarySources[].reporterStreetNullFlavor",
			"ICH.C.2.r.2.3.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_2_3,
	)?;
	validate_field(
		row,
		"reporterTelephone",
		"primarySources[].reporterTelephone",
		InputType::String,
		Some((
			"reporterTelephoneNullFlavor",
			"primarySources[].reporterTelephoneNullFlavor",
			"ICH.C.2.r.2.7.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_2_7,
	)?;
	validate_field(
		row,
		"reporterTitle",
		"primarySources[].reporterTitle",
		InputType::String,
		Some((
			"reporterTitleNullFlavor",
			"primarySources[].reporterTitleNullFlavor",
			"ICH.C.2.r.1.1.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_2_r_1_1,
	)?;
	Ok(())
}

fn sd(
	row: &Map<String, Value>,
	changed_paths: Option<&BTreeSet<String>>,
	outer_indexes: &[usize],
) -> Result<()> {
	validate_field(
		row,
		"city",
		"senderInformation.city",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_4_2,
	)?;
	validate_field(
		row,
		"countryCode",
		"senderInformation.countryCode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_4_5,
	)?;
	validate_field(
		row,
		"department",
		"senderInformation.department",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_3_1,
	)?;
	validate_field(
		row,
		"email",
		"senderInformation.email",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_4_8,
	)?;
	validate_field(
		row,
		"fax",
		"senderInformation.fax",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_4_7,
	)?;
	validate_field(
		row,
		"healthProfessionalTypeKr1",
		"senderInformation.healthProfessionalTypeKr1",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::mfds_c_3_1_kr_1,
	)?;
	validate_field(
		row,
		"organizationName",
		"senderInformation.organizationName",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_2,
	)?;
	validate_field(
		row,
		"personFamilyName",
		"senderInformation.personFamilyName",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_3_5,
	)?;
	validate_field(
		row,
		"personGivenName",
		"senderInformation.personGivenName",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_3_3,
	)?;
	validate_field(
		row,
		"personMiddleName",
		"senderInformation.personMiddleName",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_3_4,
	)?;
	validate_field(
		row,
		"personTitle",
		"senderInformation.personTitle",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_3_2,
	)?;
	validate_field(
		row,
		"postcode",
		"senderInformation.postcode",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_4_4,
	)?;
	validate_field(
		row,
		"senderType",
		"senderInformation.senderType",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_1,
	)?;
	validate_field(
		row,
		"state",
		"senderInformation.state",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_4_3,
	)?;
	validate_field(
		row,
		"streetAddress",
		"senderInformation.streetAddress",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_4_1,
	)?;
	validate_field(
		row,
		"telephone",
		"senderInformation.telephone",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_3_4_6,
	)?;
	Ok(())
}

fn si(
	row: &Map<String, Value>,
	changed_paths: Option<&BTreeSet<String>>,
	outer_indexes: &[usize],
) -> Result<()> {
	validate_field(
		row,
		"fdaCrossReportedIndNumbers[].indNumber",
		"studyInformation.fdaCrossReportedIndNumbers[].indNumber",
		InputType::String,
		Some((
			"fdaCrossReportedIndNumbers[].indNumberNullFlavor",
			"studyInformation.fdaCrossReportedIndNumbers[].indNumberNullFlavor",
			"FDA.C.5.6.r.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::fda_c_5_6_r,
	)?;
	validate_field(
		row,
		"fdaIndNumberOccurred",
		"studyInformation.fdaIndNumberOccurred",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::fda_c_5_5a,
	)?;
	validate_field(
		row,
		"fdaPreAndaNumberOccurred",
		"studyInformation.fdaPreAndaNumberOccurred",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::fda_c_5_5b,
	)?;
	validate_field(
		row,
		"sponsorStudyNumber",
		"studyInformation.sponsorStudyNumber",
		InputType::String,
		Some((
			"sponsorStudyNumberNullFlavor",
			"studyInformation.sponsorStudyNumberNullFlavor",
			"ICH.C.5.3.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_5_3,
	)?;
	validate_field(
		row,
		"studyName",
		"studyInformation.studyName",
		InputType::String,
		Some((
			"studyNameNullFlavor",
			"studyInformation.studyNameNullFlavor",
			"ICH.C.5.2.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_5_2,
	)?;
	validate_field(
		row,
		"studyRegistrationNumbers[].countryCode",
		"studyInformation.studyRegistrationNumbers[].countryCode",
		InputType::String,
		Some((
			"studyRegistrationNumbers[].countryCodeNullFlavor",
			"studyInformation.studyRegistrationNumbers[].countryCodeNullFlavor",
			"ICH.C.5.1.r.2.NULLFLAVOR.ALLOWED",
		)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_5_1_r_2,
	)?;
	validate_field(
		row,
		"studyRegistrationNumbers[].registrationNumber",
		"studyInformation.studyRegistrationNumbers[].registrationNumber",
		InputType::String,
		Some((
		"studyRegistrationNumbers[].registrationNumberNullFlavor",
		"studyInformation.studyRegistrationNumbers[].registrationNumberNullFlavor",
		"ICH.C.5.1.r.1.NULLFLAVOR.ALLOWED",
	)),
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_5_1_r_1,
	)?;
	validate_field(
		row,
		"studyTypeReaction",
		"studyInformation.studyTypeReaction",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::c_5_4,
	)?;
	validate_field(
		row,
		"studyTypeReactionKr1",
		"studyInformation.studyTypeReactionKr1",
		InputType::String,
		None,
		changed_paths,
		outer_indexes,
		input_contracts::generated::c::mfds_c_5_4_kr_1,
	)?;
	Ok(())
}
